"use client";

import { useState, type ComponentType } from "react";
import { EvaluationBodyMap, EvaluationLineChart, EvaluationStatusSummary, EvaluationTests } from "@/componentes/evaluation-insights";
import { EvaluationComparisonPanel } from "@/componentes/evaluation-progress-panels";
import { compareEvaluations } from "@/lib/evaluation-progress";
import { BmBarbellIcon, BmChevronRightIcon, BmEvaluationIcon, BmEyeIcon, BmHealthIcon, BmMeasurementsIcon, BmSlidersIcon, BmWeightIcon, type BmIconProps } from "@/componentes/icons";
import type { StudentEvaluation } from "@/types/evaluation-read-model";

type AreaKey = "comparison" | "body" | "mobility" | "physical" | "summary";
const showDate = (date: string) => date ? new Date(`${date}T12:00:00Z`).toLocaleDateString("es-AR", { timeZone: "UTC" }) : "—";
const value = (number: number | null, unit = "") => number === null ? "—" : `${new Intl.NumberFormat("es-AR", { maximumFractionDigits: 1 }).format(number)}${unit ? ` ${unit}` : ""}`;
const statusLabel = (status: StudentEvaluation["status"]) => status === "REASSESSMENT_RECOMMENDED" ? "Reevaluación recomendada" : status === "IN_PROGRESS" ? "En curso" : "Completada";
const evaluationName = (evaluation: StudentEvaluation) => evaluation.version === 1 ? "Evaluación inicial" : `Evaluación · Versión ${evaluation.version}`;

function MetricCard({ icon: Icon, label, display }: { icon: ComponentType<BmIconProps>; label: string; display: string }) {
  return <article className="flex min-w-0 items-center gap-2 rounded-2xl border border-white/[.09] bg-[#151517] px-2.5 py-3 sm:gap-3 sm:px-4"><span className="grid size-8 shrink-0 place-items-center text-[#D4A72C] sm:size-10"><Icon size={27}/></span><span className="min-w-0"><span className="block truncate text-[8px] uppercase tracking-wide text-[#6F6F75] sm:text-[10px]">{label}</span><strong className="mt-1 block truncate text-sm text-[#F5F5F5] sm:text-lg">{display}</strong></span></article>;
}

function AreaButton({ icon: Icon, title, subtitle, active, wide = false, onClick }: { icon: ComponentType<BmIconProps>; title: string; subtitle: string; active: boolean; wide?: boolean; onClick: () => void }) {
  return <button type="button" aria-expanded={active} onClick={onClick} className={`${wide ? "col-span-2" : ""} grid min-h-[4.25rem] grid-cols-[2.25rem_minmax(0,1fr)_auto] items-center gap-2 rounded-2xl border px-3 text-left outline-none transition focus-visible:ring-2 focus-visible:ring-yellow-300 ${active ? "border-yellow-400/45 bg-yellow-400/[.06]" : "border-yellow-400/20 bg-[#1B1B1E] hover:border-yellow-400/35"}`}><Icon size={25} className="text-[#D4A72C]"/><span className="min-w-0"><strong className="block text-sm leading-tight text-[#F5F5F5]">{title}</strong><small className="mt-1 block truncate text-[11px] text-[#6F6F75]">{subtitle}</small></span><BmChevronRightIcon size={18} className={`text-zinc-500 transition ${active ? "rotate-90" : ""}`}/></button>;
}

export function PortalEvaluationsDashboard({ evaluations }: { evaluations: StudentEvaluation[] }) {
  const [selectedId, setSelectedId] = useState("");
  const [activeArea, setActiveArea] = useState<AreaKey | null>(null);
  const current = evaluations.find((item) => item.id === selectedId) ?? evaluations[0];
  const index = current ? evaluations.findIndex((item) => item.id === current.id) : -1;
  const previous = index >= 0 ? evaluations[index + 1] : undefined;
  if (!current) return <p className="rounded-2xl border border-dashed border-white/[.09] bg-[#151517] p-6 text-center text-sm text-[#A3A3A8]">Todavía no hay evaluaciones completadas.</p>;
  const recentComparison = evaluations[0] && evaluations[1] ? compareEvaluations(evaluations[1], evaluations[0], new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires" }).format(new Date())) : null;
  const toggleArea = (area: AreaKey) => setActiveArea((currentArea) => currentArea === area ? null : area);

  return <div className="space-y-3 text-[#F5F5F5]">
    <section className="relative overflow-hidden rounded-[20px] border border-yellow-400/35 bg-[linear-gradient(145deg,#171717,#0B0B0C)] p-4 sm:p-6"><span aria-hidden="true" className="absolute -right-10 -top-16 size-56 rotate-12 rounded-full border border-yellow-400/[.06] shadow-[0_0_0_22px_rgba(212,167,44,.025),0_0_0_44px_rgba(212,167,44,.018)]"/><div className="relative flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#D4A72C]">Tu última evaluación</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{showDate(current.date)}</h2><p className="mt-1 text-sm text-[#A3A3A8]">{evaluationName(current)} · <span className="text-emerald-400">{statusLabel(current.status)}</span></p></div><span className="rounded-2xl border border-emerald-400/15 bg-emerald-950/30 px-3 py-2 text-xl font-black text-emerald-400 sm:px-4 sm:text-2xl">{current.completionPercentage}%</span></div><div className="relative mt-5 h-2 overflow-hidden rounded-full bg-zinc-700"><div className="h-full rounded-full bg-gradient-to-r from-yellow-400 via-lime-300 to-emerald-400" style={{ width: `${current.completionPercentage}%` }}/></div><p className="relative mt-4 text-sm text-[#A3A3A8]">Próxima evaluación: <strong className="font-medium text-zinc-200">{showDate(current.reassessmentDate)}</strong></p></section>
    <div className="grid grid-cols-3 gap-2"><MetricCard icon={BmWeightIcon} label="Peso" display={value(current.weight, "kg")}/><MetricCard icon={BmMeasurementsIcon} label="IMC" display={value(current.bmi)}/><MetricCard icon={BmHealthIcon} label="Grasa corporal" display={value(current.bodyFatPercentage, "%")}/></div>
    <section className="rounded-[20px] border border-yellow-400/20 bg-[#151517] p-4 sm:p-5"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#D4A72C]">Tu evolución</p><div className="mt-4"><EvaluationLineChart evaluations={evaluations} portalStyle/></div></section>
    <section className="rounded-[20px] border border-yellow-400/20 bg-[#151517] p-3 sm:p-4"><h2 className="px-1 text-[10px] font-bold uppercase tracking-[.2em] text-[#D4A72C]">Áreas evaluadas</h2><div className="mt-3 grid grid-cols-2 gap-2"><AreaButton icon={BmEyeIcon} title="Antes / Ahora" subtitle="Fotos y cambios" active={activeArea === "comparison"} onClick={() => toggleArea("comparison")}/><AreaButton icon={BmHealthIcon} title="Mapa corporal" subtitle="Molestias registradas" active={activeArea === "body"} onClick={() => toggleArea("body")}/><AreaButton icon={BmSlidersIcon} title="Movilidad y control" subtitle="Postura y control" active={activeArea === "mobility"} onClick={() => toggleArea("mobility")}/><AreaButton icon={BmBarbellIcon} title="Tests físicos" subtitle="Fuerza y resistencia" active={activeArea === "physical"} onClick={() => toggleArea("physical")}/><AreaButton icon={BmEvaluationIcon} title="Resumen de resultados" subtitle="Ver conclusiones completas" active={activeArea === "summary"} wide onClick={() => toggleArea("summary")}/></div>{activeArea && <div className="mt-3 rounded-2xl border border-white/[.08] bg-black/30 p-3 sm:p-4">{activeArea === "comparison" && (recentComparison ? <EvaluationComparisonPanel comparison={recentComparison} simple/> : <p className="text-sm text-[#A3A3A8]">Se necesitan al menos dos evaluaciones comparables.</p>)}{activeArea === "body" && <EvaluationBodyMap issues={current.bodyIssues}/>} {activeArea === "mobility" && <EvaluationTests tests={current.testResults} previousTests={previous?.testResults} category="MOBILITY"/>}{activeArea === "physical" && <EvaluationTests tests={current.testResults} previousTests={previous?.testResults} category="PHYSICAL"/>}{activeArea === "summary" && <EvaluationStatusSummary tests={current.testResults}/>}</div>}</section>
    <section className="rounded-[20px] border border-white/[.08] bg-[#151517] p-3 sm:p-4"><h2 className="px-1 text-[10px] font-bold uppercase tracking-[.2em] text-[#D4A72C]">Historial de evaluaciones</h2><ol className="relative ml-2 mt-3 border-l border-zinc-700 pl-5">{evaluations.map((item) => <li key={item.id} className="relative mb-2 last:mb-0"><span className="absolute -left-[26px] top-5 size-3 rounded-full bg-yellow-400 shadow-[0_0_12px_rgba(250,204,21,.35)]"/><button type="button" onClick={() => setSelectedId(item.id)} aria-label={`Ver evaluación versión ${item.version}`} className={`grid w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-3 rounded-2xl border px-3 py-2.5 text-left outline-none focus-visible:ring-2 focus-visible:ring-yellow-300 ${current.id === item.id ? "border-yellow-400/30 bg-yellow-400/[.04]" : "border-white/[.08] bg-[#1B1B1E]"}`}><span className="min-w-0"><strong className="block text-sm">Versión {item.version}</strong><time dateTime={item.date} className="mt-0.5 block text-xs text-[#A3A3A8]">{showDate(item.date)}</time><small className="mt-1 block truncate text-[11px] text-[#6F6F75]">{evaluationName(item)} · {item.weight === null ? "—" : value(item.weight, "kg")} · {item.completionPercentage}%</small></span><span className="flex items-center gap-1 text-sm font-bold text-yellow-400">Ver <BmChevronRightIcon size={17}/></span></button></li>)}</ol></section>
  </div>;
}
