"use client";

import Image from "next/image";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function PortalLoginForm() {
  const router = useRouter(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/portal/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "No se pudo iniciar sesión."); router.replace("/portal"); router.refresh(); } catch (loginError) { setError(loginError instanceof Error ? loginError.message : "No se pudo iniciar sesión."); } finally { setLoading(false); } }
  return <main className="grid min-h-screen place-items-center bg-zinc-950 p-4 text-white"><section className="w-full max-w-md rounded-3xl border border-zinc-800 bg-zinc-900 p-6 shadow-2xl sm:p-8"><div className="text-center"><Image src="/logo.png" alt="BM Coach" width={76} height={76} priority className="mx-auto h-20 w-20 object-contain" /><p className="mt-4 text-xs font-bold uppercase tracking-[.2em] text-yellow-400">Portal del alumno</p><h1 className="mt-2 text-2xl font-bold">Ingresá a tu cuenta</h1><p className="mt-2 text-sm text-zinc-500">Usá las credenciales entregadas por tu entrenador.</p></div>{error && <p role="alert" className="mt-5 rounded-xl bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}<form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm">Usuario<input required autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 outline-none focus:border-yellow-400" /></label><label className="block text-sm">Contraseña<input required type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 outline-none focus:border-yellow-400" /></label><button disabled={loading} className="w-full rounded-xl bg-yellow-400 px-4 py-3 font-bold text-zinc-950 disabled:opacity-60">{loading ? "Ingresando…" : "Iniciar sesión"}</button></form></section></main>;
}
