"use client";

import { FormEvent, useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import type { PaymentStatus, PhysicalEvaluation } from "@/types/gestion";
import type { PortalData } from "@/types/portal";

type Section = "inicio" | "rutina" | "evaluaciones" | "pagos" | "perfil";
const money = (value: number) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 }).format(value);
const date = (value: string) => value ? new Date(`${value.slice(0, 10)}T12:00:00`).toLocaleDateString("es-AR") : "—";
const number = (value: number | null, suffix = "") => value === null ? "—" : `${new Intl.NumberFormat("es-AR", { maximumFractionDigits: 1 }).format(value)}${suffix}`;
const paymentLabel = (status: PaymentStatus) => status === "proximo_a_vencer" ? "Próximo a vencer" : status.charAt(0).toUpperCase() + status.slice(1);

export function PortalSection({ section }: { section: Section }) {
  const [data, setData] = useState<PortalData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [changeRequired, setChangeRequired] = useState(false); const [reload, setReload] = useState(0);
  useEffect(() => { const controller = new AbortController(); fetch("/api/portal/data", { cache: "no-store", signal: controller.signal }).then(async (response) => { const body = await response.json() as PortalData & { error?: string; code?: string }; if (response.status === 401) { window.location.href = "/portal/login"; throw new Error("Sesión vencida."); } if (body.code === "PASSWORD_CHANGE_REQUIRED") { setChangeRequired(true); return null; } if (!response.ok) throw new Error(body.error ?? "No se pudo cargar tu información."); return body; }).then((body) => { if (body) setData(body); }).catch((loadError: unknown) => { if (loadError instanceof Error && loadError.name !== "AbortError") setError(loadError.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [reload]);
  if (loading) return <PortalLoading />;
  if (changeRequired) return <ChangePasswordCard forced onSuccess={() => { setChangeRequired(false); setLoading(true); setReload((value) => value + 1); }} />;
  if (error) return <Notice tone="error"><p>{error}</p><button onClick={() => { setLoading(true); setError(""); setReload((value) => value + 1); }} className="mt-3 rounded-lg bg-red-300 px-3 py-2 font-bold text-zinc-950">Reintentar</button></Notice>;
  if (!data) return null;
  if (section === "rutina") return <RoutineView data={data} />;
  if (section === "evaluaciones") return <EvaluationsView data={data} />;
  if (section === "pagos") return <PaymentsView data={data} />;
  if (section === "perfil") return <ProfileView data={data} />;
  return <Overview data={data} />;
}

function Overview({ data }: { data: PortalData }) {
  const latestEvaluation = data.evaluations[0]; const currentPayment = data.payments.find((payment) => payment.status !== "pagado") ?? data.payments[0];
  return <><header><p className="text-sm text-yellow-400">Hola, {data.profile.firstName}</p><h1 className="mt-1 text-2xl font-bold">Tu espacio de entrenamiento</h1><p className="mt-2 text-sm text-zinc-500">Rutina, evolución y estado de tu cuota en un solo lugar.</p></header><section className="mt-6 grid gap-4 sm:grid-cols-3"><Link href="/portal/rutina" className="rounded-2xl border border-yellow-400/20 bg-zinc-900 p-5"><p className="text-sm text-zinc-500">Rutina activa</p><p className="mt-2 text-lg font-bold text-yellow-300">{data.routine?.name ?? "Sin rutina asignada"}</p><p className="mt-2 text-xs text-zinc-500">{data.routine ? `${data.routine.objective} · ${data.routine.days.reduce((sum, day) => sum + day.exercises.length, 0)} ejercicios` : "Consultá a tu entrenador"}</p></Link><Link href="/portal/evaluaciones" className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-sm text-zinc-500">Última evaluación</p><p className="mt-2 text-lg font-bold">{latestEvaluation ? date(latestEvaluation.date) : "Sin evaluaciones"}</p><p className="mt-2 text-xs text-zinc-500">{latestEvaluation ? `${number(latestEvaluation.weight, " kg")} · IMC ${number(latestEvaluation.bmi)}` : "Todavía no hay mediciones"}</p></Link><Link href="/portal/pagos" className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-sm text-zinc-500">Estado de cuota</p><p className={`mt-2 text-lg font-bold ${currentPayment?.status === "vencido" ? "text-red-300" : currentPayment?.status === "pagado" ? "text-emerald-300" : "text-yellow-300"}`}>{currentPayment ? paymentLabel(currentPayment.status) : "Sin pagos"}</p><p className="mt-2 text-xs text-zinc-500">{currentPayment ? `${money(currentPayment.amount)} · Vence ${date(currentPayment.dueDate)}` : "Sin registros disponibles"}</p></Link></section><section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><h2 className="font-semibold text-yellow-300">Próximos eventos</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.events.length ? data.events.slice(0, 6).map((event) => <article key={event.id} className="rounded-xl border-l-4 bg-zinc-950 p-3" style={{ borderLeftColor: event.color }}><p className="font-medium">{event.title}</p><p className="mt-1 text-xs capitalize text-zinc-500">{date(event.date)} · {event.time} · {event.type}</p></article>) : <p className="text-sm text-zinc-500">No hay eventos próximos.</p>}</div></section></>;
}

function RoutineView({ data }: { data: PortalData }) {
  const routine = data.routine;
  if (!routine) return <PageHeader title="Mi rutina" subtitle="Tu planificación activa"><Notice>No tenés una rutina activa asignada. Consultá a tu entrenador.</Notice></PageHeader>;
  return <PageHeader title={routine.name} subtitle={`${routine.objective} · ${routine.level}`}><div className="space-y-4">{routine.days.map((day) => <section key={day.id} className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900"><h2 className="border-b border-zinc-800 p-4 font-bold text-yellow-300">Día {day.dayNumber} <span className="ml-2 text-xs font-normal text-zinc-500">{day.exercises.length} ejercicios</span></h2>{day.exercises.length ? <div className="divide-y divide-zinc-800">{day.exercises.map((exercise) => <article key={exercise.id} className="p-4"><div className="flex items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-yellow-400 font-bold text-zinc-950">{exercise.order}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{exercise.videoUrl ? <a href={exercise.videoUrl} target="_blank" rel="noreferrer" className="text-yellow-300 underline">{exercise.name}</a> : exercise.name}</h3><span className="text-xs text-zinc-500">{exercise.muscleGroup}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm sm:grid-cols-5"><SmallMetric title="Series" value={String(exercise.sets)} /><SmallMetric title="Repeticiones" value={exercise.repetitions} /><SmallMetric title="Peso" value={exercise.weight === null ? "—" : `${exercise.weight} kg`} /><SmallMetric title={exercise.effortType} value={exercise.effortValue === null ? "—" : String(exercise.effortValue)} /><SmallMetric title="Descanso" value={exercise.restSeconds === null ? "—" : `${exercise.restSeconds} s`} /></div>{exercise.observations && <p className="mt-3 text-sm text-zinc-400">{exercise.observations}</p>}</div></div></article>)}</div> : <p className="p-5 text-sm text-zinc-600">Día de descanso o sin ejercicios.</p>}</section>)}</div></PageHeader>;
}

function EvaluationsView({ data }: { data: PortalData }) {
  return <PageHeader title="Mis evaluaciones" subtitle="Tu evolución física"><section className="grid gap-4 sm:grid-cols-2"><EvolutionChart title="Peso" items={data.evaluations} field="weight" unit="kg" color="#facc15" /><EvolutionChart title="IMC" items={data.evaluations} field="bmi" unit="" color="#38bdf8" /><EvolutionChart title="Grasa corporal" items={data.evaluations} field="bodyFatPercentage" unit="%" color="#fb7185" /><EvolutionChart title="Masa muscular" items={data.evaluations} field="muscleMass" unit="kg" color="#34d399" /></section><section className="mt-6 overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900"><h2 className="p-4 font-semibold">Historial</h2><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="border-t border-zinc-800 text-zinc-500"><tr><th className="p-3">Fecha</th><th>Peso</th><th>IMC</th><th>Grasa</th><th>Músculo</th></tr></thead><tbody>{data.evaluations.length ? data.evaluations.map((item) => <tr key={item.id} className="border-t border-zinc-800"><td className="p-3">{date(item.date)}</td><td>{number(item.weight, " kg")}</td><td>{number(item.bmi)}</td><td>{number(item.bodyFatPercentage, "%")}</td><td>{number(item.muscleMass, " kg")}</td></tr>) : <tr><td colSpan={5} className="p-8 text-center text-zinc-500">Todavía no hay evaluaciones.</td></tr>}</tbody></table></div></section></PageHeader>;
}

function EvolutionChart({ title, items, field, unit, color }: { title: string; items: PhysicalEvaluation[]; field: "weight" | "bmi" | "bodyFatPercentage" | "muscleMass"; unit: string; color: string }) {
  const points = [...items].reverse().flatMap((item) => item[field] === null ? [] : [{ date: item.date, value: item[field] as number }]);
  if (!points.length) return <section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><h2 className="font-semibold">{title}</h2><p className="grid h-32 place-items-center text-sm text-zinc-500">Sin datos</p></section>;
  const values = points.map((point) => point.value); const min = Math.min(...values); const max = Math.max(...values); const range = max - min || 1; const coords = points.map((point, index) => ({ ...point, x: 20 + index * 280 / Math.max(points.length - 1, 1), y: 95 - (point.value - min) / range * 65 }));
  return <section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex justify-between"><h2 className="font-semibold">{title}</h2><span className="font-bold" style={{ color }}>{number(points.at(-1)?.value ?? null, unit ? ` ${unit}` : "")}</span></div><svg viewBox="0 0 320 115" className="mt-3 h-32 w-full" role="img" aria-label={`Evolución de ${title}`}><line x1="20" y1="95" x2="300" y2="95" stroke="#3f3f46" /><polyline points={coords.map((point) => `${point.x},${point.y}`).join(" ")} fill="none" stroke={color} strokeWidth="3" />{coords.map((point, index) => <circle key={`${point.date}-${index}`} cx={point.x} cy={point.y} r="4" fill={color} />)}</svg></section>;
}

function PaymentsView({ data }: { data: PortalData }) {
  return <PageHeader title="Mis pagos" subtitle="Cuotas y vencimientos"><div className="space-y-3">{data.payments.length ? data.payments.map((payment) => <article key={payment.id} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{payment.concept}</h2><p className="mt-1 text-sm text-zinc-500">Vencimiento {date(payment.dueDate)}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${payment.status === "pagado" ? "bg-emerald-400/10 text-emerald-300" : payment.status === "vencido" ? "bg-red-400/10 text-red-300" : "bg-yellow-400/10 text-yellow-300"}`}>{paymentLabel(payment.status)}</span></div><div className="mt-4 flex items-end justify-between"><p className="text-2xl font-bold">{money(payment.amount)}</p><p className="text-xs text-zinc-500">{payment.paidDate ? `Pagado ${date(payment.paidDate)} · ${payment.method}` : payment.method}</p></div>{payment.notes && <p className="mt-3 border-t border-zinc-800 pt-3 text-sm text-zinc-400">{payment.notes}</p>}</article>) : <Notice>No hay pagos registrados.</Notice>}</div></PageHeader>;
}

function ProfileView({ data }: { data: PortalData }) {
  const profile = data.profile;
  return <PageHeader title="Mi perfil" subtitle="Datos personales básicos"><section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><dl className="grid gap-4 sm:grid-cols-2"><ProfileItem title="Nombre" value={`${profile.firstName} ${profile.lastName}`} /><ProfileItem title="Teléfono" value={profile.phone} /><ProfileItem title="Correo" value={profile.email || "Sin correo"} /><ProfileItem title="Fecha de nacimiento" value={date(profile.birthDate)} /><ProfileItem title="Objetivo" value={profile.goal || "No definido"} /><ProfileItem title="Plan" value={profile.plan} /><ProfileItem title="Fecha de ingreso" value={date(profile.joinedAt)} /><ProfileItem title="Estado" value={profile.status} /></dl><p className="mt-5 text-xs text-zinc-500">Para modificar estos datos, contactá a tu entrenador.</p></section><ChangePasswordCard /></PageHeader>;
}

function ChangePasswordCard({ forced = false, onSuccess }: { forced?: boolean; onSuccess?: () => void }) {
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (newPassword !== confirmPassword) { setError("Las contraseñas nuevas no coinciden."); return; } setSaving(true); setError(""); setSuccess(""); try { const response = await fetch("/api/portal/change-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword, newPassword }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "No se pudo cambiar la contraseña."); setSuccess("Contraseña actualizada correctamente."); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); onSuccess?.(); } catch (changeError) { setError(changeError instanceof Error ? changeError.message : "No se pudo cambiar la contraseña."); } finally { setSaving(false); } }
  return <section className={`mt-6 rounded-2xl border p-5 ${forced ? "border-yellow-400/40 bg-yellow-400/5" : "border-zinc-800 bg-zinc-900"}`}><h2 className="font-semibold text-yellow-300">{forced ? "Creá tu contraseña personal" : "Cambiar contraseña"}</h2><p className="mt-1 text-sm text-zinc-500">{forced ? "La contraseña temporal debe reemplazarse antes de acceder a tus datos." : "Debe incluir mayúscula, minúscula, número y al menos 10 caracteres."}</p>{error && <p role="alert" className="mt-4 rounded-lg bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}{success && <p className="mt-4 rounded-lg bg-emerald-400/10 p-3 text-sm text-emerald-300">{success}</p>}<form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-3"><label className="text-sm">Contraseña actual<input required type="password" autoComplete="current-password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-3 outline-none focus:border-yellow-400" /></label><label className="text-sm">Nueva contraseña<input required type="password" autoComplete="new-password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-3 outline-none focus:border-yellow-400" /></label><label className="text-sm">Repetir contraseña<input required type="password" autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} className="mt-1 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 py-3 outline-none focus:border-yellow-400" /></label><button disabled={saving} className="rounded-xl bg-yellow-400 px-4 py-3 font-bold text-zinc-950 disabled:opacity-60 sm:col-span-3">{saving ? "Guardando…" : "Guardar contraseña"}</button></form></section>;
}

function PageHeader({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <><header className="mb-6"><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-sm text-zinc-500">{subtitle}</p></header>{children}</>; }
function SmallMetric({ title, value }: { title: string; value: string }) { return <div className="rounded-lg bg-zinc-950 p-2"><p className="text-[10px] text-zinc-500">{title}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function ProfileItem({ title, value }: { title: string; value: string }) { return <div><dt className="text-xs text-zinc-500">{title}</dt><dd className="mt-1 capitalize">{value}</dd></div>; }
function Notice({ children, tone = "default" }: { children: ReactNode; tone?: "default" | "error" }) { return <section className={`rounded-2xl border p-5 text-sm ${tone === "error" ? "border-red-400/30 bg-red-400/10 text-red-200" : "border-zinc-800 bg-zinc-900 text-zinc-400"}`}>{children}</section>; }
function PortalLoading() { return <div className="animate-pulse space-y-4"><div className="h-8 w-48 rounded bg-zinc-800" /><div className="h-4 w-72 rounded bg-zinc-900" /><div className="grid gap-4 sm:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <div key={index} className="h-32 rounded-2xl bg-zinc-900" />)}</div><div className="h-64 rounded-2xl bg-zinc-900" /></div>; }
