"use client";

import { useEffect, useMemo, useState } from "react";
import { ModuleShell, inputClass } from "@/componentes/module-shell";
import { EvaluationBodyMap, EvaluationLineChart, EvaluationStatusSummary, EvaluationTests } from "@/componentes/evaluation-insights";
import { BMProgressCard, EvaluationComparisonPanel, EvaluationGlobalDashboard, EvaluationSymmetryPanel } from "@/componentes/evaluation-progress-panels";
import { compareEvaluations } from "@/lib/evaluation-progress";
import { interpretEvaluation } from "@/lib/evaluation-interpretation";
import type { NormalizedEvaluation } from "@/types/evaluation-read-model";
import type { EvaluationGlobalStats, EvaluationStudentSummary } from "@/types/evaluation-progress";

const showDate = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("es-AR") : "—";
const value = (number: number | null, unit = "") => number === null ? "—" : `${new Intl.NumberFormat("es-AR", { maximumFractionDigits: 1 }).format(number)}${unit ? ` ${unit}` : ""}`;
const service = { CLASSES: "Clases presenciales", PERSONALIZED: "Rutina personalizada", MIXED: "Servicio mixto" } as const;
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires" }).format(new Date());
const daysBetween = (from: string, to: string) => Math.max(0, Math.round((Date.parse(`${to}T12:00:00`) - Date.parse(`${from}T12:00:00`)) / 86400000));

function Panel({ title, subtitle, children, open = false }: { title: string; subtitle?: string; children: React.ReactNode; open?: boolean }) {
  return <details open={open} className="rounded-2xl border border-zinc-800 bg-zinc-900/80"><summary className="cursor-pointer list-none p-4 focus:outline-none focus:ring-2 focus:ring-yellow-400"><div className="flex items-center justify-between gap-4"><div><h2 className="font-bold">{title}</h2>{subtitle && <p className="mt-1 text-xs text-zinc-500">{subtitle}</p>}</div><span className="text-yellow-400">⌄</span></div></summary><div className="border-t border-zinc-800 p-4">{children}</div></details>;
}

export function ProfessionalEvaluationsDashboard() {
  const [evaluations, setEvaluations] = useState<NormalizedEvaluation[]>([]); const [students, setStudents] = useState<EvaluationStudentSummary[]>([]); const [stats, setStats] = useState<EvaluationGlobalStats | null>(null);
  const [studentId, setStudentId] = useState(""); const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState(""); const [baseId, setBaseId] = useState(""); const [recentId, setRecentId] = useState(""); const [comparisonOpen, setComparisonOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("studentId") ?? ""; fetch("/api/admin/evaluaciones/progreso").then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "No se pudieron cargar las evaluaciones."); return payload as { evaluations: NormalizedEvaluation[]; students: EvaluationStudentSummary[]; stats: EvaluationGlobalStats }; }).then((payload) => { setEvaluations(payload.evaluations); setStudents(payload.students); setStats(payload.stats); if (requested) setStudentId(requested); }).catch((cause: Error) => setError(cause.message)).finally(() => setLoading(false)); }, []);
  const matches = useMemo(() => students.filter((item) => `${item.firstName} ${item.lastName}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8), [students, query]);
  const history = useMemo(() => evaluations.filter((item) => item.studentId === studentId).sort((a, b) => b.date.localeCompare(a.date) || b.version - a.version), [evaluations, studentId]);
  const current = history.find((item) => item.id === selectedId) ?? history[0]; const currentIndex = current ? history.findIndex((item) => item.id === current.id) : -1; const previous = currentIndex >= 0 ? history[currentIndex + 1] : undefined; const student = students.find((item) => item.id === studentId);
  const chosenRecent = history.find((item) => item.id === recentId) ?? history[0]; const chosenBase = history.find((item) => item.id === baseId) ?? history[1]; const comparison = chosenBase && chosenRecent && chosenBase.id !== chosenRecent.id ? compareEvaluations(chosenBase, chosenRecent, today()) : null;
  const latestComparison = history[1] && history[0] ? compareEvaluations(history[1], history[0], today()) : null; const fullComparison = history.length > 1 ? compareEvaluations(history.at(-1)!, history[0], today()) : null;
  const automaticInterpretation = current ? interpretEvaluation(current, today()) : null;
  const chooseStudent = (id: string, name: string) => { setStudentId(id); setSelectedId(""); setBaseId(""); setRecentId(""); setComparisonOpen(false); setQuery(name); };
  const compareWithPrevious = (item: NormalizedEvaluation, prior: NormalizedEvaluation) => { setRecentId(item.id); setBaseId(prior.id); setComparisonOpen(true); };
  if (loading) return <ModuleShell title="Evaluaciones" subtitle="Seguimiento profesional"><p className="rounded-xl bg-zinc-900 p-5 text-zinc-400">Cargando evaluaciones…</p></ModuleShell>;
  return <ModuleShell title="Evaluaciones" subtitle="Seguimiento profesional y evolución del alumno">
    {error && <p className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</p>}
    {stats && <EvaluationGlobalDashboard stats={stats} onStudent={chooseStudent}/>}
    <section className="mb-5 rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><label className="text-xs font-bold uppercase tracking-wider text-zinc-500">Buscar alumno</label><input className={`${inputClass} mt-2`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nombre o apellido"/><div className="mt-2 flex flex-wrap gap-2">{matches.map((item) => <button type="button" key={item.id} onClick={() => chooseStudent(item.id, `${item.firstName} ${item.lastName}`)} className={`rounded-full px-3 py-2 text-xs font-bold ${studentId === item.id ? "bg-yellow-400 text-black" : "bg-zinc-800 text-zinc-300"}`}>{item.firstName} {item.lastName}</button>)}</div></section>
    {!studentId ? <p className="rounded-2xl border border-dashed border-zinc-700 p-8 text-center text-zinc-500">Seleccioná un alumno para abrir su dashboard profesional.</p> : !current ? <p className="rounded-2xl border border-dashed border-zinc-700 p-8 text-center text-zinc-500">El alumno seleccionado todavía no tiene evaluaciones registradas.</p> : <div className="space-y-4">
      <header className="rounded-2xl border border-yellow-400/15 bg-[linear-gradient(145deg,#181818,#090909)] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-yellow-400">Dashboard del alumno</p><h2 className="mt-2 text-2xl font-black">{current.studentName || `${student?.firstName ?? ""} ${student?.lastName ?? ""}`.trim()}</h2><p className="mt-1 text-sm text-zinc-400">{student ? service[student.serviceType] : "Servicio no informado"} · {current.age === null ? "Edad no informada" : `${current.age} años`}</p><p className="mt-2 text-sm"><span className="text-zinc-500">Objetivo:</span> {current.primaryGoal || student?.goal || "Sin registro"}</p></div><div className="text-right"><p className="text-xs text-zinc-500">Última evaluación</p><p className="font-bold">{showDate(history[0].date)}</p><p className="mt-2 text-xs text-zinc-500">Próxima reevaluación</p><p className="font-bold">{showDate(history[0].reassessmentDate)}</p></div></div></header>
      <div className="grid gap-3 md:grid-cols-[minmax(250px,1.3fr)_repeat(4,minmax(0,1fr))]">{latestComparison ? <BMProgressCard progress={latestComparison.progress} compact/> : <BMProgressCard progress={{ available: false, score: null, reason: "Se necesitan al menos dos evaluaciones comparables.", formula: "", components: [] }} compact/>}{[["Evaluaciones",history.length],["Días desde última",daysBetween(history[0].date,today())],["Prioridades actuales",automaticInterpretation?.priorities.length ?? 0],["Alertas activas",automaticInterpretation?.alerts.length ?? 0]].map(([label, display]) => <article key={label} className="rounded-xl border border-zinc-800 bg-zinc-900 p-3"><p className="text-[10px] text-zinc-500">{label}</p><p className="mt-2 text-2xl font-black">{display}</p></article>)}</div>
      {fullComparison && <Panel title="Desde la primera evaluación" subtitle="Resumen del período completo" open><div className="grid grid-cols-2 gap-2 md:grid-cols-4"><article className="rounded-lg bg-black/30 p-3"><p className="text-xs text-zinc-500">Tiempo de seguimiento</p><p className="mt-1 font-bold">{fullComparison.elapsedDays} días</p></article><article className="rounded-lg bg-black/30 p-3"><p className="text-xs text-zinc-500">Evaluaciones</p><p className="mt-1 font-bold">{history.length}</p></article>{fullComparison.measurements.filter((item) => ["weight","waist","bodyFatPercentage"].includes(item.key)).map((item) => <article key={item.key} className="rounded-lg bg-black/30 p-3"><p className="text-xs text-zinc-500">Cambio de {item.label.toLowerCase()}</p><p className="mt-1 font-bold">{item.absoluteChange > 0 ? "+" : ""}{value(item.absoluteChange,item.unit)}</p></article>)}<article className="rounded-lg bg-black/30 p-3"><p className="text-xs text-zinc-500">Tests con evolución</p><p className="mt-1 font-bold">{fullComparison.tests.filter((item) => item.compatible && (item.absoluteChange ?? 0) > 0).length}</p></article><article className="rounded-lg bg-black/30 p-3"><p className="text-xs text-zinc-500">Prioridades ya no activas</p><p className="mt-1 font-bold">{fullComparison.progress.components.find((item) => item.key === "PRIORITIES")?.usedData[0] ?? "Datos insuficientes"}</p></article></div></Panel>}
      <Panel title="Evolución corporal" subtitle="Peso, perímetros y composición ordenados cronológicamente" open><EvaluationLineChart evaluations={history}/></Panel>
      {comparisonOpen && <Panel title="Comparar evaluaciones" subtitle="Sólo se muestran cambios compatibles" open><div className="mb-4 grid gap-2 sm:grid-cols-2"><label className="text-xs text-zinc-500">Evaluación base<select className={`${inputClass} mt-1`} value={chosenBase?.id ?? ""} onChange={(event) => setBaseId(event.target.value)}>{history.map((item) => <option key={item.id} value={item.id}>Versión {item.version} · {showDate(item.date)}</option>)}</select></label><label className="text-xs text-zinc-500">Evaluación más reciente<select className={`${inputClass} mt-1`} value={chosenRecent?.id ?? ""} onChange={(event) => setRecentId(event.target.value)}>{history.map((item) => <option key={item.id} value={item.id}>Versión {item.version} · {showDate(item.date)}</option>)}</select></label></div>{comparison ? <EvaluationComparisonPanel comparison={comparison}/> : <p className="text-sm text-zinc-500">Elegí dos evaluaciones diferentes.</p>}</Panel>}
      <div className="grid gap-4 lg:grid-cols-2"><Panel title="Simetría actual" subtitle="Medidas y tests con ambos lados"><EvaluationSymmetryPanel items={latestComparison?.symmetry ?? []}/></Panel><Panel title="Mapa corporal actual" subtitle="Molestias informadas y observación profesional"><EvaluationBodyMap issues={current.bodyIssues} privateDetails/></Panel></div>
      <Panel title="Movilidad y control" subtitle="Estados y resultados comparables"><EvaluationTests tests={current.testResults} previousTests={previous?.testResults} category="MOBILITY" privateDetails/></Panel>
      <Panel title="Rendimiento físico" subtitle="Sólo compara protocolo, unidad y variante compatibles"><EvaluationTests tests={current.testResults} previousTests={previous?.testResults} category="PHYSICAL" privateDetails/></Panel>
      <Panel title="Prioridades y estado general"><EvaluationStatusSummary tests={current.testResults}/>{automaticInterpretation && <div className="mt-4 grid gap-2 sm:grid-cols-2">{automaticInterpretation.priorities.map((item) => <article key={item.id} className="rounded-lg bg-black/35 p-3"><p className="text-sm font-semibold">{item.message}</p><details className="mt-2"><summary className="cursor-pointer text-xs font-bold text-yellow-300">¿Por qué?</summary><div className="mt-2 space-y-1 text-xs text-zinc-500"><p><strong className="text-zinc-300">Dato observado:</strong> {item.evidence}</p><p><strong className="text-zinc-300">Interpretación:</strong> {item.message}</p><p><strong className="text-zinc-300">Impacto posible:</strong> revisar la planificación de {item.category}; no implica diagnóstico.</p><p><strong className="text-zinc-300">Sugerencia:</strong> {item.recommendation}</p></div></details></article>)}</div>}</Panel>
      <Panel title="Resumen profesional" subtitle="Información privada, sólo para el entrenador"><div className="grid gap-3 sm:grid-cols-2">{[["Fortalezas",current.finalStrengths],["Prioridades",current.finalPriorities],["Limitaciones",current.finalLimitations],["Planificación",current.planningNotes],["Comentario final",current.finalComment]].map(([label, display]) => <article key={label} className="rounded-xl bg-black/35 p-4"><p className="text-xs font-bold text-yellow-400">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-300">{display || "—"}</p></article>)}</div></Panel>
      <Panel title="Historial" subtitle="Timeline de versiones deduplicadas"><ol className="relative ml-2 border-l border-zinc-700 pl-5">{history.map((item, index) => <li key={item.id} className="relative mb-4 rounded-xl bg-black/35 p-3 last:mb-0"><span className="absolute -left-[26px] top-4 h-3 w-3 rounded-full border-2 border-zinc-900 bg-yellow-400"/><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">Versión {item.version} · {showDate(item.date)}</p><p className="mt-1 text-xs text-zinc-500">{item.status.replaceAll("_", " ")} · {item.completionPercentage}%</p><p className="mt-1 text-xs text-zinc-400">{[item.primaryGoal, item.weight === null ? "" : value(item.weight,"kg")].filter(Boolean).join(" · ")}</p></div><div className="flex gap-2"><button type="button" onClick={() => setSelectedId(item.id)} className="rounded-lg bg-yellow-400 px-3 py-2 text-xs font-bold text-black">Ver</button>{index < history.length - 1 && <button type="button" onClick={() => compareWithPrevious(item, history[index + 1])} className="rounded-lg border border-zinc-700 px-3 py-2 text-xs font-bold text-zinc-300">Comparar</button>}</div></div></li>)}</ol></Panel>
    </div>}
  </ModuleShell>;
}
