"use client";

import { useEffect, useMemo, useState } from "react";
import { ModuleShell, inputClass } from "@/componentes/module-shell";
import { EvaluationBodyMap, EvaluationLineChart, EvaluationStatusSummary, EvaluationTests } from "@/componentes/evaluation-insights";
import type { NormalizedEvaluation } from "@/types/evaluation-read-model";
import type { Student } from "@/types/gestion";
import { interpretEvaluation } from "@/lib/evaluation-interpretation";

const showDate = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("es-AR") : "—";
const value = (number: number | null, unit = "") => number === null ? "—" : `${new Intl.NumberFormat("es-AR", { maximumFractionDigits: 1 }).format(number)}${unit ? ` ${unit}` : ""}`;
const service = { CLASSES: "Clases presenciales", PERSONALIZED: "Rutina personalizada", MIXED: "Servicio mixto" } as const;

function Panel({ title, subtitle, children, open = false }: { title: string; subtitle?: string; children: React.ReactNode; open?: boolean }) {
  return <details open={open} className="rounded-2xl border border-zinc-800 bg-zinc-900/80"><summary className="cursor-pointer list-none p-4 focus:outline-none focus:ring-2 focus:ring-yellow-400"><div className="flex items-center justify-between gap-4"><div><h2 className="font-bold">{title}</h2>{subtitle && <p className="mt-1 text-xs text-zinc-500">{subtitle}</p>}</div><span className="text-yellow-400">⌄</span></div></summary><div className="border-t border-zinc-800 p-4">{children}</div></details>;
}

export function ProfessionalEvaluationsDashboard() {
  const [evaluations, setEvaluations] = useState<NormalizedEvaluation[]>([]); const [students, setStudents] = useState<Student[]>([]);
  const [studentId, setStudentId] = useState(""); const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("studentId") ?? ""; Promise.all([fetch("/api/evaluaciones").then((r) => { if (!r.ok) throw new Error("No se pudieron cargar las evaluaciones."); return r.json(); }), fetch("/api/alumnos").then((r) => r.ok ? r.json() : [])]).then(([items, studentItems]: [NormalizedEvaluation[], Student[]]) => { setEvaluations(items); setStudents(studentItems); const initial = requested || items[0]?.studentId || studentItems[0]?.id || ""; setStudentId(initial); }).catch((cause: Error) => setError(cause.message)).finally(() => setLoading(false)); }, []);
  const matches = useMemo(() => students.filter((item) => `${item.firstName} ${item.lastName}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8), [students, query]);
  const history = useMemo(() => evaluations.filter((item) => item.studentId === studentId).sort((a, b) => b.date.localeCompare(a.date) || b.version - a.version), [evaluations, studentId]);
  const current = history.find((item) => item.id === selectedId) ?? history[0]; const currentIndex = current ? history.findIndex((item) => item.id === current.id) : -1; const previous = currentIndex >= 0 ? history[currentIndex + 1] : undefined; const student = students.find((item) => item.id === studentId);
  if (loading) return <ModuleShell title="Evaluaciones" subtitle="Seguimiento profesional"><p className="rounded-xl bg-zinc-900 p-5 text-zinc-400">Cargando evaluaciones…</p></ModuleShell>;
  const chooseStudent = (id: string, name: string) => { setStudentId(id); setSelectedId(""); setQuery(name); };
  const automaticInterpretation = current ? interpretEvaluation(current, new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires" }).format(new Date())) : null;
  return <ModuleShell title="Evaluaciones" subtitle="Historia clínica deportiva y evolución del alumno">
    {error && <p className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</p>}
    <section className="mb-5 rounded-2xl border border-zinc-800 bg-zinc-900 p-4"><label className="text-xs font-bold uppercase tracking-wider text-zinc-500">Alumno</label><input className={`${inputClass} mt-2`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nombre"/><div className="mt-2 flex flex-wrap gap-2">{matches.map((item) => <button type="button" key={item.id} onClick={() => chooseStudent(item.id, `${item.firstName} ${item.lastName}`)} className={`rounded-full px-3 py-2 text-xs font-bold ${studentId === item.id ? "bg-yellow-400 text-black" : "bg-zinc-800 text-zinc-300"}`}>{item.firstName} {item.lastName}</button>)}</div></section>
    {!current ? <p className="rounded-2xl border border-dashed border-zinc-700 p-8 text-center text-zinc-500">El alumno seleccionado todavía no tiene evaluaciones registradas.</p> : <div className="space-y-4">
      <header className="rounded-2xl border border-yellow-400/15 bg-[linear-gradient(145deg,#181818,#090909)] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-yellow-400">Seguimiento profesional</p><h2 className="mt-2 text-2xl font-black">{current.studentName || (student ? `${student.firstName} ${student.lastName}` : "Alumno")}</h2><p className="mt-1 text-sm text-zinc-400">{student ? service[student.serviceType] : "Servicio no informado"} · {current.age === null ? "Edad no informada" : `${current.age} años`}</p></div><div className="text-right"><p className="font-bold">{showDate(current.date)}</p><p className="mt-1 text-xs text-zinc-500">{history.length} evaluaciones · versión {current.version}</p><span className="mt-2 inline-flex rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-bold text-emerald-300">{current.status === "REASSESSMENT_RECOMMENDED" ? "Reevaluación recomendada" : current.status === "IN_PROGRESS" ? "En curso" : "Completada"}</span></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-zinc-800"><div className="h-full bg-gradient-to-r from-yellow-500 to-emerald-400" style={{ width: `${current.completionPercentage}%` }}/></div></header>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{[["Peso", value(current.weight,"kg")],["IMC",value(current.bmi)],["Grasa",value(current.bodyFatPercentage,"%")],["Disponibilidad",current.weeklyAvailability || "—"],["Evaluaciones",String(history.length)],["Reevaluación",showDate(current.reassessmentDate)]].map(([label, display]) => <article key={label} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-2 font-black text-zinc-100">{display}</p></article>)}</div>
      <Panel title="Mediciones actuales" subtitle="Sólo valores realmente registrados"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{[["Peso",current.weight,"kg"],["Altura",current.height,"m"],["Edad",current.age,"años"],["IMC",current.bmi,""],["Grasa corporal",current.bodyFatPercentage,"%"],["Masa muscular",current.muscleMass,"kg"],["Cintura",current.waist,"cm"],["Cadera",current.hip,"cm"],["Pecho",current.chest,"cm"],["Brazo derecho",current.rightArm,"cm"],["Brazo izquierdo",current.leftArm,"cm"],["Muslo derecho",current.rightThigh,"cm"],["Muslo izquierdo",current.leftThigh,"cm"],["Pantorrilla derecha",current.rightCalf,"cm"],["Pantorrilla izquierda",current.leftCalf,"cm"]].filter(([, measured]) => measured !== null).map(([label, measured, unit]) => <article key={label as string} className="rounded-xl bg-black/35 p-3"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 font-bold">{value(measured as number, unit as string)}</p></article>)}</div></Panel>
      <Panel title="Evolución corporal" subtitle="Datos comparables ordenados cronológicamente" open><EvaluationLineChart evaluations={history}/></Panel>
      <Panel title="Mapa corporal" subtitle="Molestias, intensidad y observación profesional"><EvaluationBodyMap issues={current.bodyIssues} privateDetails/></Panel>
      <Panel title="Movilidad y control motor" subtitle="Ocho pruebas estandarizadas"><EvaluationTests tests={current.testResults} previousTests={previous?.testResults} category="MOBILITY" privateDetails/></Panel>
      <Panel title="Rendimiento físico" subtitle="La variación sólo aparece si protocolo, unidad y variante son comparables"><EvaluationTests tests={current.testResults} previousTests={previous?.testResults} category="PHYSICAL" privateDetails/></Panel>
      <Panel title="Resumen de evaluación" subtitle="Distribución de estados reales, sin puntaje artificial"><EvaluationStatusSummary tests={current.testResults}/></Panel>
      {automaticInterpretation && <Panel title="Interpretación automática" subtitle="Reglas deterministas para asistir la planificación; el entrenador decide"><div className="grid gap-4 lg:grid-cols-2"><section><h3 className="text-sm font-bold text-emerald-300">Fortalezas</h3>{automaticInterpretation.strengths.length ? <ul className="mt-2 space-y-2 text-sm text-zinc-300">{automaticInterpretation.strengths.map((item) => <li key={item} className="rounded-lg bg-emerald-400/5 p-2">{item}</li>)}</ul> : <p className="mt-2 text-sm text-zinc-500">Sin fortalezas categóricas suficientes.</p>}</section><section><h3 className="text-sm font-bold text-yellow-300">Prioridades</h3><div className="mt-2 space-y-2">{automaticInterpretation.priorities.map((item) => <article key={item.id} className="rounded-lg bg-black/35 p-3"><p className="text-sm font-semibold">{item.message}</p><p className="mt-1 text-xs text-zinc-500">Dato original: {item.evidence}</p><p className="mt-2 text-xs text-zinc-300">Sugerencia: {item.recommendation}</p></article>)}</div></section></div>{automaticInterpretation.alerts.length > 0 && <div className="mt-4 grid gap-2 sm:grid-cols-2">{automaticInterpretation.alerts.map((item) => <p key={item.id} className="rounded-lg bg-orange-400/10 p-3 text-sm text-orange-200">{item.message}</p>)}</div>}</Panel>}
      <Panel title="Perfil de entrenamiento"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Objetivo principal",current.primaryGoal],["Objetivos secundarios",current.secondaryGoals.join(", ")],["Experiencia",current.experienceLevel],["Actividades",current.activities],["Disponibilidad",current.weeklyAvailability],["Sueño",[current.habits.sleepHours,current.habits.sleepQuality].filter(Boolean).join(" h · ")],["Estrés",String(current.habits.stress ?? "")],["Actividad diaria",String(current.habits.dailyActivity ?? "")]].filter(([, display]) => Boolean(display)).map(([label, display]) => <article key={label as string} className="rounded-xl bg-black/35 p-3"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-sm font-semibold">{String(display)}</p></article>)}</div></Panel>
      <Panel title="Resumen profesional" subtitle="Información privada, visible sólo para el entrenador"><div className="grid gap-3 sm:grid-cols-2">{[["Fortalezas",current.finalStrengths],["Prioridades",current.finalPriorities],["Limitaciones",current.finalLimitations],["Planificación",current.planningNotes],["Comentario final",current.finalComment]].map(([label, display]) => <article key={label} className="rounded-xl bg-black/35 p-4"><p className="text-xs font-bold text-yellow-400">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-300">{display || "—"}</p></article>)}</div></Panel>
      <Panel title="Historial" subtitle="Todas las versiones, sin mezclar registros duplicados"><div className="space-y-2">{history.map((item, index) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-black/35 p-3"><div><p className="font-bold">Versión {item.version} · {showDate(item.date)}</p><p className="mt-1 text-xs text-zinc-500">{item.status.replaceAll("_", " ")} · {item.completionPercentage}%</p><p className="mt-1 text-xs text-zinc-400">{[item.primaryGoal, item.weight === null ? "" : value(item.weight,"kg"), item.bodyFatPercentage === null ? "" : value(item.bodyFatPercentage,"% grasa")].filter(Boolean).join(" · ")}</p></div><div className="flex gap-2"><button type="button" onClick={() => setSelectedId(item.id)} className="rounded-lg bg-yellow-400 px-3 py-2 text-xs font-bold text-black">Ver evaluación</button>{index < history.length - 1 && <button type="button" onClick={() => setSelectedId(item.id)} className="rounded-lg border border-zinc-700 px-3 py-2 text-xs font-bold text-zinc-300">Comparar con anterior</button>}</div></article>)}</div></Panel>
    </div>}
  </ModuleShell>;
}
