"use client";

import { useMemo, useRef, useState } from "react";
import { inputClass } from "@/componentes/module-shell";
import type { LatestEvaluationContext } from "@/componentes/routine-evaluation-panel";
import type { Student } from "@/types/gestion";
import type { RoutineAIConstraints, RoutineAIDay, RoutineAIProposal } from "@/types/routine-ai";

type Props = { student: Student | undefined; evaluationContext: LatestEvaluationContext | null; objective: string; level: string; location: string; equipment: string[]; onApply: (days: RoutineAIDay[], proposal: RoutineAIProposal) => void };

export function RoutineAIProposalPanel({ student, evaluationContext, objective, level, location, equipment, onApply }: Props) {
  const available = Number(evaluationContext?.evaluation?.weeklyAvailability.match(/\d+/)?.[0] ?? 3); const [requestedDays, setRequestedDays] = useState(Math.max(1, Math.min(available || 3, 6))); const [sessionMinutes, setSessionMinutes] = useState<number | null>(60); const [environment, setEnvironment] = useState<RoutineAIConstraints["location"]>(location.toLowerCase().includes("casa") ? "HOME" : location.toLowerCase().includes("gimnasio") ? "FULL_GYM" : location ? "CUSTOM" : "SALON_BM"); const [instructions, setInstructions] = useState(""); const [proposal, setProposal] = useState<RoutineAIProposal | null>(null); const [selectedDays, setSelectedDays] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [reviewed, setReviewed] = useState(false); const requestInFlight = useRef(false);
  const eligible = student && student.serviceType !== "CLASSES" && Boolean(objective.trim() && level.trim()); const unresolved = useMemo(() => proposal?.days.flatMap((day) => day.blocks.flatMap((block) => block.exercises)).filter((exercise) => !exercise.resolved) ?? [], [proposal]); const needsReview = Boolean(proposal?.validationWarnings.length || unresolved.length);
  if (!student || student.serviceType === "CLASSES") return null;
  const studentId = student.id;

  async function generate() {
    if (!eligible || requestInFlight.current) return; requestInFlight.current = true; setLoading(true); setError(""); setReviewed(false);
    try { const response = await fetch("/api/admin/rutinas/propuesta", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "generate", studentId, requestKey: crypto.randomUUID(), constraints: { requestedDays, sessionMinutes, location: environment, equipment, trainerInstructions: instructions } }) }); const payload = await response.json() as { proposal?: RoutineAIProposal; error?: string }; if (!response.ok || !payload.proposal) throw new Error(payload.error || "No se pudo generar la propuesta."); setProposal(payload.proposal); setSelectedDays(payload.proposal.days.map((day) => day.id)); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo generar la propuesta. Podés continuar creando la rutina manualmente."); }
    finally { requestInFlight.current = false; setLoading(false); }
  }

  function replaceExercise(dayId: string, blockId: string, exerciseId: string, name: string) { if (!proposal) return; setProposal({ ...proposal, days: proposal.days.map((day) => day.id !== dayId ? day : { ...day, blocks: day.blocks.map((block) => block.id !== blockId ? block : { ...block, exercises: block.exercises.map((exercise) => exercise.id !== exerciseId ? exercise : { ...exercise, name, resolved: true, resolutionSource: "KNOWN_NAME" }) }) }) }); }
  async function alternatives(dayId: string, blockId: string, exerciseId: string, exerciseName: string) { const response = await fetch("/api/admin/rutinas/propuesta", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "alternatives", studentId, exerciseName }) }); const payload = await response.json().catch(() => ({})) as { alternatives?: string[] }; const chosen = payload.alternatives?.length ? window.prompt(`Alternativas:\n${payload.alternatives.map((item, index) => `${index + 1}. ${item}`).join("\n")}\n\nEscribí el número:`, "1") : null; const index = chosen ? Number(chosen) - 1 : -1; if (payload.alternatives?.[index]) replaceExercise(dayId, blockId, exerciseId, payload.alternatives[index]); }
  function apply() { if (!proposal || !selectedDays.length || needsReview && !reviewed) return; onApply(proposal.days.filter((day) => selectedDays.includes(day.id)), proposal); setProposal(null); }

  return <section className="mt-5 rounded-xl border border-violet-400/25 bg-violet-400/[.04] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-violet-300">Asistencia de planificación</p><p className="mt-1 text-sm text-zinc-400">La IA propone. Vos revisás, aplicás y guardás manualmente.</p></div><button type="button" onClick={generate} disabled={!eligible || loading} className="min-h-10 rounded-lg bg-violet-300 px-4 text-sm font-black text-violet-950 disabled:opacity-50">{loading ? "Generando…" : proposal ? "Regenerar" : "✨ Generar propuesta"}</button></div>
    {!evaluationContext?.evaluation && <p className="mt-3 rounded-lg bg-yellow-400/10 p-2 text-xs text-yellow-200">Sin evaluación reciente. La propuesta tendrá menor contexto.</p>}
    <details className="mt-3"><summary className="cursor-pointer text-xs font-bold text-zinc-300">Restricciones e indicaciones</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs">Días<input type="number" min="1" max={Math.min(available || 6, 6)} value={requestedDays} onChange={(event) => setRequestedDays(Number(event.target.value))} className={`${inputClass} mt-1`}/></label><label className="text-xs">Minutos por sesión<input type="number" min="20" max="180" value={sessionMinutes ?? ""} onChange={(event) => setSessionMinutes(event.target.value ? Number(event.target.value) : null)} className={`${inputClass} mt-1`}/></label><label className="text-xs">Entorno<select value={environment} onChange={(event) => setEnvironment(event.target.value as RoutineAIConstraints["location"])} className={`${inputClass} mt-1`}><option value="SALON_BM">Salón BM</option><option value="FULL_GYM">Gimnasio completo</option><option value="HOME">Casa</option><option value="CUSTOM">Personalizado</option></select></label><label className="text-xs sm:col-span-2 lg:col-span-4">Indicaciones para la propuesta<textarea value={instructions} onChange={(event) => setInstructions(event.target.value)} maxLength={800} rows={2} placeholder="Ej.: prefiero ejercicios simples, 45 minutos, evitar burpees…" className={`${inputClass} mt-1`}/></label></div></details>
    {error && <p role="alert" className="mt-3 rounded-lg bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
    {proposal && <div className="mt-4 border-t border-zinc-800 pt-4"><h3 className="font-black">Propuesta de planificación</h3><p className="mt-1 text-sm text-zinc-400">{proposal.summary}</p><p className="mt-2 text-xs text-zinc-500">Frecuencia: {proposal.weeklyFrequency} días · {proposal.weeklyStructure.join(" · ")}</p>
      {proposal.rationale.length > 0 && <details className="mt-3 rounded-lg bg-black/25 p-3"><summary className="cursor-pointer text-sm font-bold">Por qué se propone esta estructura</summary><ul className="mt-2 space-y-1 text-xs text-zinc-400">{proposal.rationale.map((item, index) => <li key={index}>• {item.statement} <span className="text-zinc-600">({item.evidenceIds.join(", ") || "objetivo/restricciones"})</span></li>)}</ul></details>}
      <div className="mt-3 grid gap-3 lg:grid-cols-2">{proposal.days.map((day) => <article key={day.id} className="rounded-xl border border-zinc-800 bg-black/25 p-3"><label className="flex items-start gap-2"><input type="checkbox" checked={selectedDays.includes(day.id)} onChange={(event) => setSelectedDays((items) => event.target.checked ? [...items, day.id] : items.filter((id) => id !== day.id))}/><span><strong>{day.name}</strong><span className="block text-xs text-zinc-500">{day.focus} · {day.estimatedMinutes ?? "—"} min</span></span></label><div className="mt-3 space-y-2">{day.blocks.map((block) => <div key={block.id} className="rounded-lg bg-zinc-900 p-2"><p className="text-xs font-bold text-violet-300">{block.type} · {block.name}</p>{block.exercises.map((exercise) => <div key={exercise.id} className="mt-2 rounded-md bg-black/30 p-2"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm font-semibold">{exercise.name}{!exercise.resolved && <span className="ml-2 text-[10px] text-orange-300">No resuelto</span>}</span><button type="button" onClick={() => alternatives(day.id, block.id, exercise.id, exercise.name)} className="text-[11px] font-bold text-violet-300">Cambiar ejercicio</button></div><p className="text-[11px] text-zinc-500">{exercise.sets} × {exercise.repetitions} · descanso {exercise.restSeconds ?? "—"}s</p><details><summary className="cursor-pointer text-[11px] text-zinc-400">¿Por qué este ejercicio?</summary><p className="mt-1 text-[11px] text-zinc-500">{exercise.rationale || "Relacionado con el objetivo y la estructura del bloque."} {exercise.evidenceIds.length ? `Datos: ${exercise.evidenceIds.join(", ")}.` : ""}</p></details></div>)}</div>)}</div></article>)}</div>
      <div className="mt-3 grid gap-2 sm:grid-cols-2"><p className="rounded-lg bg-emerald-400/5 p-3 text-xs text-emerald-200">Prioridades consideradas: {proposal.prioritiesCovered.join(", ") || "Ninguna verificable"}</p><p className="rounded-lg bg-yellow-400/5 p-3 text-xs text-yellow-200">Prioridades pendientes: {proposal.prioritiesPending.join(", ") || "Ninguna"}</p></div>
      {needsReview && <label className="mt-3 flex items-start gap-2 rounded-lg bg-orange-400/10 p-3 text-xs text-orange-200"><input type="checkbox" checked={reviewed} onChange={(event) => setReviewed(event.target.checked)}/><span>Revisé las advertencias y ejercicios no resueltos: {[...proposal.validationWarnings, ...unresolved.map((item) => item.name)].join(" · ")}</span></label>}
      <div className="mt-4 flex flex-wrap justify-end gap-2"><button type="button" onClick={() => setProposal(null)} className="rounded-lg border border-zinc-700 px-3 py-2 text-xs">Descartar</button><button type="button" onClick={generate} disabled={loading} className="rounded-lg border border-violet-300/40 px-3 py-2 text-xs text-violet-200">Regenerar</button><button type="button" onClick={apply} disabled={!selectedDays.length || needsReview && !reviewed} className="rounded-lg border border-violet-300/40 px-3 py-2 text-xs text-violet-200 disabled:opacity-40">Editar en el creador</button><button type="button" onClick={apply} disabled={!selectedDays.length || needsReview && !reviewed} className="rounded-lg bg-violet-300 px-4 py-2 text-xs font-black text-violet-950 disabled:opacity-40">{selectedDays.length === proposal.days.length ? "Aplicar propuesta" : "Aplicar parcialmente"}</button></div>
    </div>}
  </section>;
}
