"use client";
/* eslint-disable @next/next/no-img-element -- profile photos are validated object-storage URLs */

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { inputClass } from "@/componentes/module-shell";
import { CardGridSkeleton, EmptyState, ErrorState, ListSkeleton } from "@/componentes/async-states";
import { BodyEvolutionChart, ExerciseProgressChart, SessionDurationChart, TrainingDistributionChart } from "@/componentes/routine-follow-up-charts";
import { DEFAULT_PROFILE_AVATAR } from "@/lib/profile-avatars";
import { routineTrainingLocation, type RoutineTrainingLocation } from "@/lib/routine-follow-up-filters";
import type { AdminFollowUpDetail, AdminFollowUpState, AdminStudentFollowUp, AdminWorkoutExercise, AdminWorkoutSession } from "@/types/follow-up";

type SummaryResponse = { students: AdminStudentFollowUp[]; summary: Summary; error?: string };
type Summary = { trackedStudents: number; onTrack: number; onTrackPercentage: number; attention: number; attentionPercentage: number; averageSessions: number };
type Tab = "resumen" | "sesiones" | "progreso" | "molestias";
const emptySummary: Summary = { trackedStudents: 0, onTrack: 0, onTrackPercentage: 0, attention: 0, attentionPercentage: 0, averageSessions: 0 };
const pageSize = 6;
const showDate = (value: string) => new Date(`${value.slice(0, 10)}T12:00:00`).toLocaleDateString("es-AR");
const valueOrDash = (value: number | null, suffix = "") => value === null ? "—" : `${new Intl.NumberFormat("es-AR", { maximumFractionDigits: 1 }).format(value)}${suffix}`;
const stateLabels: Record<AdminFollowUpState, string> = { on_track: "Al día", attention: "Necesita atención", no_data: "Sin datos" };

export function RoutineFollowUpDashboard({ initialStudentId = "" }: { initialStudentId?: string }) {
  const [students, setStudents] = useState<AdminStudentFollowUp[]>([]);
  const [summary, setSummary] = useState(emptySummary);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [reload, setReload] = useState(0);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<"all" | AdminFollowUpState>("all");
  const [location, setLocation] = useState<"all" | RoutineTrainingLocation>("all");
  const [page, setPage] = useState(1);
  const [selectedStudent, setSelectedStudent] = useState<AdminStudentFollowUp | null>(null);
  const [detail, setDetail] = useState<AdminFollowUpDetail | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [detailError, setDetailError] = useState("");
  const [tab, setTab] = useState<Tab>("resumen");
  const [selectedSession, setSelectedSession] = useState<AdminWorkoutSession | null>(null);
  const openerRef = useRef<HTMLElement | null>(null);

  const loadSummary = useCallback(async () => {
    const response = await fetch("/api/seguimiento/resumen", { cache: "no-store" });
    const body = await response.json() as SummaryResponse;
    if (!response.ok) throw new Error(body.error ?? "No se pudo cargar el seguimiento.");
    setStudents(body.students); setSummary(body.summary);
  }, []);

  useEffect(() => { const controller = new AbortController();
    fetch("/api/seguimiento/resumen", { cache: "no-store", signal: controller.signal }).then(async (response) => {
      if (response.status === 401 || response.status === 403) { window.location.assign("/admin/login"); throw new Error("Sesión vencida."); }
      const body = await response.json() as SummaryResponse; if (!response.ok) throw new Error("No pudimos cargar el seguimiento."); setStudents(body.students); setSummary(body.summary); setError("");
    }).catch((value: unknown) => { if (!(value instanceof Error && value.name === "AbortError")) setError(value instanceof Error ? value.message : "No pudimos cargar el seguimiento."); })
      .finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort();
  }, [reload]);

  const openStudent = useCallback(async (student: AdminStudentFollowUp, preferredTab: Tab = "resumen") => {
    openerRef.current = document.activeElement as HTMLElement | null; setSelectedStudent(student); setTab(preferredTab); setDetail(null); setDetailLoading(true); setDetailError("");
    try { const response = await fetch(`/api/seguimiento/detalle?studentId=${encodeURIComponent(student.studentId)}`, { cache: "no-store" });
      const body = await response.json() as AdminFollowUpDetail & { error?: string }; if (!response.ok) throw new Error(response.status === 404 ? "Este seguimiento ya no está disponible." : "No pudimos cargar el detalle del alumno."); setDetail(body);
    } catch (value) { setDetailError(value instanceof Error ? value.message : "No pudimos cargar el detalle del alumno."); }
    finally { setDetailLoading(false); }
  }, []);

  useEffect(() => { if (!initialStudentId || !students.length || selectedStudent) return; const student = students.find((item) => item.studentId === initialStudentId); if (!student) return; const timer = window.setTimeout(() => void openStudent(student), 0); return () => window.clearTimeout(timer); }, [initialStudentId, openStudent, selectedStudent, students]);
  const closeDetail = useCallback(() => { setSelectedStudent(null); setDetail(null); setSelectedSession(null); window.setTimeout(() => openerRef.current?.focus(), 0); }, []);

  const visible = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("es"); return students.filter((student) =>
    (!normalized || student.studentName.toLocaleLowerCase("es").includes(normalized) || student.activeRoutine?.name.toLocaleLowerCase("es").includes(normalized))
    && (status === "all" || student.state === status)
    && (location === "all" || routineTrainingLocation(student.activeRoutine?.location ?? "") === location));
  }, [location, query, status, students]);
  const pages = Math.max(1, Math.ceil(visible.length / pageSize));
  const paged = visible.slice((page - 1) * pageSize, page * pageSize);
  const attention = students.filter((student) => student.state === "attention").slice(0, 4);
  const hasFilters = Boolean(query) || status !== "all" || location !== "all";
  const retrySummary = () => { setError(""); setLoading(true); setReload((value) => value + 1); };

  return <section aria-labelledby="follow-up-title">
    <header className="mb-4"><p className="text-[10px] font-black uppercase tracking-[.2em] text-yellow-400">Control de entrenamiento</p><div className="mt-1 flex flex-wrap items-end justify-between gap-2"><div><h2 id="follow-up-title" className="text-2xl font-black text-zinc-100">Seguimiento</h2><p className="mt-1 text-sm text-zinc-500">Adherencia, evolución y señales reales de cada plan activo.</p></div><p className="text-[11px] text-zinc-600">Cumplimiento sobre semanas completas del plan</p></div></header>
    {error && students.length > 0 && <div className="mb-4"><ErrorState compact title="No pudimos actualizar el seguimiento." retry={retrySummary} /></div>}
    {error && students.length === 0 ? null : loading && students.length === 0 ? <CardGridSkeleton /> : <div className="grid grid-cols-2 gap-2 lg:grid-cols-4"><Metric label="Alumnos en seguimiento" value={String(summary.trackedStudents)} helper="Con rutina activa" /><Metric label="Al día" value={`${summary.onTrackPercentage}%`} helper={`${summary.onTrack} alumnos`} tone="green" /><Metric label="Necesitan atención" value={`${summary.attentionPercentage}%`} helper={`${summary.attention} alumnos`} tone="red" /><Metric label="Promedio por alumno" value={String(summary.averageSessions)} helper="Sesiones completadas" /></div>}
    {!loading && attention.length > 0 && <section className="mt-4 rounded-2xl border border-red-400/15 bg-red-400/[.035] p-3"><div className="flex items-center justify-between"><h3 className="text-sm font-black">Necesitan atención · {summary.attention}</h3><span className="text-[10px] text-zinc-500">Prioridades reales</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{attention.map((student) => <button key={student.studentId} type="button" onClick={() => void openStudent(student, student.latestPainReport ? "molestias" : "resumen")} className="min-h-12 rounded-xl border border-zinc-800 bg-black/30 px-3 py-2 text-left hover:border-red-400/30"><strong className="block truncate text-xs text-zinc-200">{student.studentName}</strong><span className="mt-1 block truncate text-[11px] text-red-300/80">{student.attentionReason}</span></button>)}</div></section>}
    <div className="mt-4 grid gap-2 rounded-2xl border border-zinc-800 bg-[#111] p-3 sm:grid-cols-[1fr_180px_180px_auto]"><input type="search" value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Buscar alumno o rutina" aria-label="Buscar alumno o rutina" className={inputClass} /><select value={status} onChange={(event) => { setStatus(event.target.value as typeof status); setPage(1); }} aria-label="Estado de seguimiento" className={inputClass}><option value="all">Todos los estados</option><option value="on_track">Al día</option><option value="attention">Necesita atención</option><option value="no_data">Sin datos</option></select><select value={location} onChange={(event) => { setLocation(event.target.value as typeof location); setPage(1); }} aria-label="Lugar de entrenamiento" className={inputClass}><option value="all">Todos los lugares</option><option value="gym">Gimnasio</option><option value="studio">Salón</option><option value="home">Casa</option></select><button type="button" disabled={!hasFilters} onClick={() => { setQuery(""); setStatus("all"); setLocation("all"); setPage(1); }} className="min-h-11 px-3 text-sm font-bold text-yellow-300 disabled:text-zinc-600">Limpiar</button></div>
    <div aria-busy={loading} className="mt-3 overflow-hidden rounded-2xl border border-zinc-800 bg-[#111]">{loading && students.length === 0 ? <div className="p-3"><ListSkeleton rows={5} /></div> : error && students.length === 0 ? <div className="p-4"><ErrorState title="No pudimos cargar el seguimiento." retry={() => setReload((value) => value + 1)} /></div> : paged.length ? <><div className="hidden grid-cols-[1.25fr_1.25fr_100px_70px_90px_95px_125px_48px] gap-3 border-b border-zinc-800 px-4 py-3 text-[10px] font-bold uppercase tracking-wider text-zinc-500 lg:grid"><span>Alumno</span><span>Rutina activa</span><span>Última sesión</span><span>Sesiones</span><span>Promedio</span><span>Cumplimiento</span><span>Estado</span><span /></div><div className="divide-y divide-zinc-800">{paged.map((student) => <StudentRow key={student.studentId} student={student} open={() => void openStudent(student)} />)}</div><Pagination page={page} pages={pages} count={visible.length} setPage={setPage} /></> : <div className="p-4"><EmptyState title={hasFilters ? "No encontramos alumnos con estos filtros." : "Todavía no hay sesiones para mostrar seguimiento."} description={hasFilters ? "Probá limpiar la búsqueda o cambiar los filtros." : "El seguimiento aparecerá cuando los alumnos completen entrenamientos."} action={hasFilters ? <button type="button" onClick={() => { setQuery(""); setStatus("all"); setLocation("all"); }} className="min-h-11 px-4 text-sm font-bold text-yellow-300">Limpiar filtros</button> : undefined} /></div>}</div>
    {selectedStudent && <StudentDrawer student={selectedStudent} detail={detail} loading={detailLoading} error={detailError} retry={() => void openStudent(selectedStudent, tab)} tab={tab} setTab={setTab} close={closeDetail} openSession={setSelectedSession} suspended={Boolean(selectedSession)} />}
    {selectedSession && <SessionDialog session={selectedSession} close={() => setSelectedSession(null)} changed={async () => { await loadSummary(); if (selectedStudent) await openStudent(selectedStudent, "sesiones"); }} />}
  </section>;
}

function Metric({ label, value, helper, tone = "gold" }: { label: string; value: string; helper: string; tone?: "gold" | "green" | "red" }) { const color = tone === "green" ? "text-emerald-300" : tone === "red" ? "text-red-300" : "text-yellow-300"; return <article className="rounded-2xl border border-zinc-800 bg-[#111] p-3 sm:p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-500">{label}</p><p className={`mt-1 text-2xl font-black ${color}`}>{value}</p><p className="mt-1 text-[11px] text-zinc-600">{helper}</p></article>; }

function StudentRow({ student, open }: { student: AdminStudentFollowUp; open: () => void }) {
  return <article className="p-4 transition hover:bg-white/[.02]"><div className="lg:hidden"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><img src={student.profileImageUrl || DEFAULT_PROFILE_AVATAR.src} alt="" className="size-10 rounded-full border border-yellow-400/20 object-cover" /><div className="min-w-0"><h3 className="truncate text-sm font-bold">{student.studentName}</h3><p className="truncate text-xs text-yellow-300">{student.activeRoutine?.name}</p></div></div><Status state={student.state} /></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><Small label="Última" value={student.latestSession ? showDate(student.latestSession.date) : "Sin datos"} /><Small label="Sesiones" value={String(student.sessionCount)} /><Small label="Cumplimiento" value={student.compliancePercentage === null ? "Sin datos" : `${student.compliancePercentage}%`} /></div><button type="button" onClick={open} className="mt-3 min-h-11 w-full rounded-xl border border-yellow-400/20 text-xs font-bold text-yellow-300 outline-none transition hover:border-yellow-400/40 focus-visible:ring-2 focus-visible:ring-yellow-300">Ver seguimiento</button></div><div className="hidden grid-cols-[1.25fr_1.25fr_100px_70px_90px_95px_125px_48px] items-center gap-3 lg:grid"><div className="flex min-w-0 items-center gap-3"><img src={student.profileImageUrl || DEFAULT_PROFILE_AVATAR.src} alt="" className="size-9 rounded-full border border-yellow-400/20 object-cover" /><strong className="truncate text-sm">{student.studentName}</strong></div><span className="truncate text-xs text-yellow-300">{student.activeRoutine?.name}</span><span className="text-xs text-zinc-300">{student.latestSession ? showDate(student.latestSession.date) : "Sin datos"}</span><span className="text-xs">{student.sessionCount}</span><span className="text-xs">{student.averageDuration ? `${student.averageDuration} min` : "—"}</span><span className="text-xs">{student.compliancePercentage === null ? "Sin datos" : `${student.compliancePercentage}%`}</span><Status state={student.state} /><button type="button" onClick={open} aria-label={`Ver seguimiento de ${student.studentName}`} className="grid size-11 place-items-center rounded-xl border border-zinc-700 text-yellow-300 outline-none transition hover:border-yellow-400/50 focus-visible:ring-2 focus-visible:ring-yellow-300">↗</button></div></article>;
}
function Status({ state }: { state: AdminFollowUpState }) { const tone = state === "on_track" ? "bg-emerald-400/10 text-emerald-300" : state === "attention" ? "bg-red-400/10 text-red-300" : "bg-zinc-700 text-zinc-300"; return <span className={`rounded-full px-2 py-1 text-center text-[10px] font-bold ${tone}`}>{stateLabels[state]}</span>; }
function Small({ label, value }: { label: string; value: string }) { return <span className="min-w-0"><small className="block text-zinc-600">{label}</small><span className="block truncate text-zinc-300">{value}</span></span>; }
function Pagination({ page, pages, count, setPage }: { page: number; pages: number; count: number; setPage: (page: number) => void }) { return <footer className="flex items-center justify-between border-t border-zinc-800 px-4 py-3 text-xs text-zinc-500"><span>{count} alumnos</span><div className="flex items-center gap-2"><button type="button" aria-label="Página anterior" disabled={page <= 1} onClick={() => setPage(page - 1)} className="size-11 rounded-xl border border-zinc-800 transition hover:border-yellow-400/30 hover:text-yellow-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-300 disabled:opacity-30">‹</button><span aria-live="polite">{page} / {pages}</span><button type="button" aria-label="Página siguiente" disabled={page >= pages} onClick={() => setPage(page + 1)} className="size-11 rounded-xl border border-zinc-800 transition hover:border-yellow-400/30 hover:text-yellow-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-300 disabled:opacity-30">›</button></div></footer>; }

function StudentDrawer({ student, detail, loading, error, retry, tab, setTab, close, openSession, suspended }: { student: AdminStudentFollowUp; detail: AdminFollowUpDetail | null; loading: boolean; error: string; retry: () => void; tab: Tab; setTab: (tab: Tab) => void; close: () => void; openSession: (session: AdminWorkoutSession) => void; suspended: boolean }) {
  const closeButton = useRef<HTMLButtonElement>(null); const [exerciseId, setExerciseId] = useState("");
  useEffect(() => { closeButton.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !suspended) close(); }; document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, [close, suspended]);
  const selectedExerciseId = exerciseId || detail?.exerciseProgress[0]?.exerciseId || "";
  const sessions = detail?.sessions ?? []; const completed = sessions.filter((item) => item.status === "completed"); const pain = sessions.filter((item) => item.hasPain);
  return <div className="fixed inset-0 z-40 bg-black/75 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><section role="dialog" aria-modal="true" aria-label={`Seguimiento de ${student.studentName}`} className="ml-auto flex h-dvh w-full flex-col border-l border-yellow-400/15 bg-[#0b0b0d] shadow-2xl lg:w-[62vw] xl:max-w-[1180px]"><header className="sticky top-0 z-10 border-b border-zinc-800 bg-[#0b0b0d]/95 px-4 py-4 backdrop-blur sm:px-6"><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><img src={student.profileImageUrl || DEFAULT_PROFILE_AVATAR.src} alt="" className="size-12 rounded-full border border-yellow-400/30 object-cover" /><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-wider text-yellow-400">Seguimiento del alumno</p><h2 className="truncate text-xl font-black">{student.studentName}</h2><p className="truncate text-xs text-zinc-500">{student.activeRoutine?.name} · {student.activeRoutine?.location || "Lugar sin definir"}</p></div><Status state={student.state} /></div><button ref={closeButton} onClick={close} aria-label="Cerrar seguimiento" className="grid size-11 shrink-0 place-items-center rounded-xl border border-zinc-800 text-xl text-zinc-400 transition hover:border-yellow-400/30 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-300">×</button></div><nav role="tablist" aria-label="Detalle de seguimiento" className="mt-3 flex gap-3 overflow-x-auto">{([ ["resumen", "Resumen"], ["sesiones", "Sesiones"], ["progreso", "Progreso"], ["molestias", "Molestias"] ] as Array<[Tab, string]>).map(([value, label]) => <button key={value} type="button" role="tab" aria-selected={tab === value} onClick={() => setTab(value)} className={`min-h-11 shrink-0 border-b-2 px-2 text-sm font-bold outline-none transition focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-yellow-300 ${tab === value ? "border-yellow-400 text-yellow-300" : "border-transparent text-zinc-500 hover:text-zinc-200"}`}>{label}</button>)}</nav></header>
    <div aria-busy={loading} className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-6">{loading ? <><CardGridSkeleton cards={4} /><div className="mt-4"><ListSkeleton rows={4} cardHeight="h-24" /></div></> : error || !detail ? <ErrorState title="No pudimos cargar el detalle del alumno." description={error} retry={retry} /> : <><div className="grid grid-cols-2 gap-2 xl:grid-cols-6"><DetailMetric label="Sesiones" value={String(student.sessionCount)} /><DetailMetric label="Última" value={student.latestSession ? showDate(student.latestSession.date) : "Sin datos"} /><DetailMetric label="Duración media" value={student.averageDuration ? `${student.averageDuration} min` : "Sin datos"} /><DetailMetric label="Ejercicios" value={String(student.exerciseCount)} /><DetailMetric label="Series" value={String(student.completedSets)} /><DetailMetric label="Cumplimiento" value={student.compliancePercentage === null ? "Sin datos" : `${student.compliancePercentage}%`} /></div>
      {tab === "resumen" && <div role="tabpanel" className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Sesiones recientes" action={<button onClick={() => setTab("sesiones")} className="text-xs text-yellow-300">Ver todas →</button>}>{completed.length ? <div className="divide-y divide-zinc-800">{completed.slice(0, 5).map((session) => <button key={session.id} onClick={() => openSession(session)} className="grid w-full grid-cols-[1fr_auto] gap-3 py-3 text-left"><span><strong className="block truncate text-sm">{session.routine} · Día {session.dayNumber}</strong><small className="text-zinc-500">{showDate(session.date)} · {session.exerciseCount} ejercicios</small></span><span className="text-xs text-zinc-400">{session.durationMinutes ? `${session.durationMinutes} min` : "—"}</span></button>)}</div> : <Empty />}</Panel><Panel title="Evolución corporal"><BodyEvolutionChart evaluations={detail?.evaluations ?? []} /></Panel><Panel title="Cumplimiento del plan"><Compliance student={student} /></Panel><Panel title="Duración por sesión"><SessionDurationChart sessions={completed} /></Panel><Panel title="Distribución por tipo de bloque"><TrainingDistributionChart items={detail?.blockDistribution ?? []} /></Panel></div>}
      {tab === "sesiones" && <div role="tabpanel" className="mt-4 space-y-2">{sessions.length ? sessions.map((session) => <button key={session.id} onClick={() => openSession(session)} className="grid w-full grid-cols-[1fr_auto] items-center gap-3 rounded-xl border border-zinc-800 bg-[#111] p-4 text-left"><span><strong className="block text-sm">{session.routine} · Día {session.dayNumber}</strong><small className="text-zinc-500">{showDate(session.date)} · {session.exerciseCount} ejercicios · {session.completedSets} series</small></span><span className="text-xs font-bold text-yellow-300">Ver detalle</span></button>) : <Empty />}</div>}
      {tab === "progreso" && <div role="tabpanel" className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Evolución de cargas" action={detail?.exerciseProgress.length ? <select aria-label="Ejercicio" value={selectedExerciseId} onChange={(event) => setExerciseId(event.target.value)} className="max-w-52 rounded-lg border border-zinc-700 bg-black px-2 py-1 text-xs">{detail.exerciseProgress.map((item) => <option key={item.exerciseId} value={item.exerciseId}>{item.name}</option>)}</select> : null}><ExerciseProgressChart exercise={detail?.exerciseProgress.find((item) => item.exerciseId === selectedExerciseId) ?? null} /></Panel><Panel title="Evolución corporal"><BodyEvolutionChart evaluations={detail?.evaluations ?? []} /></Panel></div>}
      {tab === "molestias" && <div role="tabpanel" className="mt-4 space-y-3">{pain.length ? pain.map((session) => <button key={session.id} onClick={() => openSession(session)} className="w-full rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-left"><strong className="text-sm text-red-200">{showDate(session.date)} · {session.routine}</strong><p className="mt-2 text-sm text-red-100">{session.painDetails || "Sin detalle informado."}</p></button>) : <Empty text="No hay molestias registradas." />}</div>}
    </>}</div></section></div>;
}

function DetailMetric({ label, value }: { label: string; value: string }) { return <article className="rounded-xl border border-zinc-800 bg-[#111] p-3"><p className="text-[10px] text-zinc-500">{label}</p><p className="mt-1 truncate text-sm font-bold">{value}</p></article>; }
function Panel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-2xl border border-zinc-800 bg-[#111] p-4"><header className="mb-3 flex items-center justify-between gap-3"><h3 className="text-sm font-black">{title}</h3>{action}</header>{children}</section>; }
function Compliance({ student }: { student: AdminStudentFollowUp }) { if (student.compliancePercentage === null) return <Empty text="El plan todavía no completó una semana medible." />; return <div><div className="flex items-end justify-between"><strong className="text-3xl text-yellow-300">{student.compliancePercentage}%</strong><span className="text-xs text-zinc-500">{student.sessionCount} / {student.expectedSessionCount} sesiones</span></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-zinc-800"><div className="h-full rounded-full bg-yellow-400" style={{ width: `${student.compliancePercentage}%` }} /></div><p className="mt-3 text-xs text-zinc-500">Se cuentan sólo semanas completas desde la asignación o inicio del plan.</p></div>; }
function Empty({ text = "Sin datos disponibles." }: { text?: string }) { return <p className="rounded-xl border border-dashed border-zinc-800 p-8 text-center text-sm text-zinc-500">{text}</p>; }

function SessionDialog({ session, close, changed }: { session: AdminWorkoutSession; close: () => void; changed: () => Promise<void> }) {
  const [reply, setReply] = useState(""); const [privateNote, setPrivateNote] = useState(""); const [reviewed, setReviewed] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === "Escape") close(); }; document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, [close]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const operations = [reply.trim() ? { body: reply, private: false } : null, privateNote.trim() ? { body: privateNote, private: true } : null, reviewed ? { reviewed: true } : null].filter(Boolean); for (const operation of operations) { const response = await fetch("/api/seguimiento", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sessionId: session.id, ...operation }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "No se pudo guardar."); } setReply(""); setPrivateNote(""); setReviewed(false); await changed(); } catch (value) { setError(value instanceof Error ? value.message : "No se pudo guardar."); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/85 p-3"><section role="dialog" aria-modal="true" aria-labelledby="session-detail-title" className="mx-auto my-4 max-w-5xl rounded-2xl border border-zinc-800 bg-zinc-900 p-4 sm:p-5"><header className="flex justify-between gap-4"><div className="min-w-0"><p className="text-xs uppercase tracking-wider text-yellow-400">Detalle del entrenamiento</p><h2 id="session-detail-title" className="mt-1 text-xl font-bold">{session.routine} · Día {session.dayNumber}</h2><p className="text-sm text-zinc-500">{showDate(session.date)} · {session.durationMinutes ? `${session.durationMinutes} min` : "Sin duración"}</p></div><button type="button" onClick={close} aria-label="Cerrar detalle" className="grid size-11 shrink-0 place-items-center rounded-xl border border-zinc-700 text-xl transition hover:border-yellow-400/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-300">×</button></header>{error && <p className="mt-3 text-sm text-red-300">{error}</p>}<div className="mt-5 space-y-3">{session.exercises.map((exercise) => <Exercise key={exercise.id} exercise={exercise} />)}</div><form onSubmit={submit} className="mt-5 rounded-xl border border-yellow-400/20 bg-black/30 p-4"><h3 className="font-bold text-yellow-300">Devolución del entrenador</h3><textarea value={reply} onChange={(event) => setReply(event.target.value)} rows={3} placeholder="Respuesta visible para el alumno" className={`${inputClass} mt-3`} /><textarea value={privateNote} onChange={(event) => setPrivateNote(event.target.value)} rows={2} placeholder="Nota privada de esta sesión" className={`${inputClass} mt-3`} /><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={reviewed} onChange={(event) => setReviewed(event.target.checked)} className="accent-yellow-400" /> Marcar comentarios como revisados</label><button disabled={saving || (!reply.trim() && !privateNote.trim() && !reviewed)} className="mt-4 min-h-11 w-full rounded-xl bg-yellow-400 font-bold text-black disabled:opacity-40">{saving ? "Guardando…" : "Guardar devolución"}</button></form></section></div>;
}
function Exercise({ exercise }: { exercise: AdminWorkoutExercise }) { return <details className="rounded-xl border border-zinc-800 bg-black/30"><summary className="cursor-pointer p-4 font-bold">{exercise.name} <span className="ml-2 text-xs font-normal text-zinc-500">{exercise.sets.filter((set) => set.completed).length} series completadas</span></summary><div className="border-t border-zinc-800 p-4"><div className="grid gap-2 sm:grid-cols-2">{exercise.sets.map((set) => <div key={set.id} className="rounded-lg bg-zinc-900 p-3 text-xs"><strong>Serie {set.setNumber}</strong><p className="mt-1 text-zinc-400">{valueOrDash(set.weight, " kg")} · {valueOrDash(set.repetitions, " reps")} · esfuerzo {valueOrDash(set.effort)}</p></div>)}</div>{exercise.studentObservation && <p className="mt-3 text-sm text-zinc-400">Observación: {exercise.studentObservation}</p>}</div></details>; }
