"use client";

import { useState } from "react";

type AccessStatus = { exists: boolean; username?: string; active: boolean; mustChangePassword?: boolean; temporaryPassword?: string };

export function StudentAccessControls({ studentId }: { studentId: string }) {
  const [adminToken, setAdminToken] = useState(""); const [status, setStatus] = useState<AccessStatus | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [credentials, setCredentials] = useState<{ username: string; password: string } | null>(null);
  function token() { if (adminToken) return adminToken; const entered = window.prompt("Ingresá la clave administrativa del portal:")?.trim() ?? ""; if (entered) setAdminToken(entered); return entered; }
  async function request(method: "GET" | "POST" | "PATCH", body?: object) { const authorization = token(); if (!authorization) return null; setLoading(true); setError(""); try { const response = await fetch(`/api/admin/alumnos/${studentId}/acceso`, { method, headers: { "x-bm-admin-token": authorization, ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined }); const result = await response.json() as AccessStatus & { error?: string }; if (!response.ok) { if (response.status === 401) setAdminToken(""); throw new Error(result.error ?? "No se pudo gestionar el acceso."); } setStatus(result); if (result.temporaryPassword && result.username) setCredentials({ username: result.username, password: result.temporaryPassword }); return result; } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "No se pudo gestionar el acceso."); return null; } finally { setLoading(false); } }
  async function copyCredentials() { if (!credentials) return; await navigator.clipboard.writeText(`Usuario: ${credentials.username}\nContraseña temporal: ${credentials.password}\nAcceso: ${window.location.origin}/portal/login`); }
  return <section className="mt-5 rounded-xl border border-yellow-400/25 bg-yellow-400/5 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold text-yellow-300">Acceso al Portal del Alumno</h3><p className="mt-1 text-xs text-zinc-500">Estado: {status ? status.exists ? status.active ? "Activo" : "Inactivo" : "Sin acceso" : "Protegido · consultar"}{status?.mustChangePassword ? " · cambio de contraseña pendiente" : ""}</p>{status?.username && <p className="mt-1 text-xs text-zinc-400">Usuario: {status.username}</p>}</div><button disabled={loading} onClick={() => request("GET")} className="rounded-lg border border-zinc-700 px-3 py-2 text-xs text-yellow-300">{loading ? "Procesando…" : "Consultar estado"}</button></div>{error && <p role="alert" className="mt-3 rounded-lg bg-red-400/10 p-3 text-xs text-red-300">{error}</p>}{credentials && <div className="mt-4 rounded-xl border border-yellow-400/30 bg-black p-4"><p className="text-xs font-bold uppercase text-yellow-400">Entregar una sola vez</p><p className="mt-2 text-sm">Usuario: <strong>{credentials.username}</strong></p><p className="mt-1 text-sm">Contraseña temporal: <strong>{credentials.password}</strong></p><button onClick={copyCredentials} className="mt-3 rounded-lg bg-yellow-400 px-3 py-2 text-xs font-bold text-zinc-950">Copiar credenciales</button></div>}<div className="mt-4 flex flex-wrap gap-2">{(!status || !status.exists) && <button disabled={loading} onClick={() => request("POST")} className="rounded-lg bg-yellow-400 px-3 py-2 text-xs font-bold text-zinc-950">Crear acceso</button>}{status?.exists && <button disabled={loading} onClick={() => request("PATCH", { action: "reset" })} className="rounded-lg border border-yellow-400/40 px-3 py-2 text-xs text-yellow-300">Restablecer contraseña</button>}{status?.exists && status.active && <button disabled={loading} onClick={() => request("PATCH", { action: "deactivate" })} className="rounded-lg border border-red-400/40 px-3 py-2 text-xs text-red-300">Desactivar acceso</button>}{status?.exists && !status.active && <button disabled={loading} onClick={() => request("PATCH", { action: "activate" })} className="rounded-lg border border-emerald-400/40 px-3 py-2 text-xs text-emerald-300">Activar acceso</button>}</div></section>;
}
