"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { inputClass } from "@/componentes/module-shell";

export function TrainerOnboarding({ initial }: { initial: { name: string; brandName: string; city: string; serviceType: string } }) {
  const router = useRouter(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (saving) return; setSaving(true); setError(""); const form = new FormData(event.currentTarget); const body = Object.fromEntries(["name", "brandName", "city", "serviceType"].map((key) => [key, String(form.get(key) ?? "")])); try { const response = await fetch("/api/trainer/onboarding", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string; next?: string }; if (!response.ok) throw new Error(result.error || "No se pudo guardar."); router.replace(result.next || "/dashboard"); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar."); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="w-full max-w-xl rounded-3xl border border-yellow-400/20 bg-zinc-900 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-yellow-400">Tu espacio está casi listo</p><h1 className="mt-2 text-3xl font-black">Perfil de entrenador</h1><p className="mt-2 text-sm text-zinc-400">Confirmá cómo querés presentarte en BM Training.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm sm:col-span-2">Nombre visible<input name="name" required defaultValue={initial.name} maxLength={120} className={`${inputClass} mt-1`}/></label><label className="text-sm">Marca o gimnasio<input name="brandName" defaultValue={initial.brandName} maxLength={120} className={`${inputClass} mt-1`}/></label><label className="text-sm">Ciudad (opcional)<input name="city" defaultValue={initial.city} maxLength={120} className={`${inputClass} mt-1`}/></label><label className="text-sm sm:col-span-2">Tipo de servicio<select name="serviceType" required defaultValue={initial.serviceType || "MIXED"} className={`${inputClass} mt-1`}><option value="CLASSES">Clases</option><option value="PERSONALIZED">Personalizado</option><option value="MIXED">Mixto</option><option value="ONLINE">Online</option></select></label></div>{error && <p role="alert" className="mt-4 rounded-xl bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}<button disabled={saving} className="mt-6 min-h-12 w-full rounded-xl bg-yellow-400 font-black text-zinc-950 disabled:opacity-60">{saving ? "Guardando…" : "Entrar a mi dashboard"}</button></form>;
}
