import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePlatformOwnerPage } from "@/lib/platform-auth";
import { prisma } from "@/lib/prisma";
import { effectiveTrainerSubscriptionStatus } from "@/lib/trainer-subscription";
import { TrainerMembershipDetailManager } from "@/componentes/trainer-membership-detail-manager";

function showDate(value: Date | null | undefined) { return value ? value.toLocaleDateString("es-AR") : "Sin definir"; }
const labels = { ACTIVE: "Al día", PAST_DUE: "Vencido", SUSPENDED: "Suspendido", CANCELLED: "Cancelado" } as const;

export default async function TrainerDetailPage({ params }: PageProps<"/platform/trainers/[id]">) {
  await requirePlatformOwnerPage();
  const { id } = await params;
  const trainer = await prisma.user.findFirst({ where: { id, platformRole: "TRAINER", memberships: { some: { role: "OWNER", workspace: { type: "PROFESSIONAL" } } } }, select: { id: true, name: true, email: true, phone: true, brandName: true, city: true, serviceType: true, status: true, onboardingCompleted: true, createdAt: true, trainerSubscription: true, memberships: { where: { role: "OWNER", workspace: { type: "PROFESSIONAL" } }, select: { workspace: { select: { name: true, status: true, _count: { select: { students: true } } } } } } } });
  if (!trainer) notFound();
  const subscription = trainer.trainerSubscription;
  const effective = subscription ? effectiveTrainerSubscriptionStatus(subscription) : null;
  const workspace = trainer.memberships[0]?.workspace;
  const serializedSubscription = subscription ? { ...subscription, startedAt: subscription.startedAt.toISOString(), lastPaidAt: subscription.lastPaidAt?.toISOString() ?? null, currentPeriodEnd: subscription.currentPeriodEnd?.toISOString() ?? null, nextDueAt: subscription.nextDueAt?.toISOString() ?? null, createdAt: undefined, updatedAt: undefined, trainerUserId: undefined } : null;
  return <main className="px-4 py-8 sm:px-6 lg:px-10"><div className="mx-auto max-w-5xl"><Link href="/platform/trainers" className="text-sm font-bold text-yellow-300">← Volver a entrenadores</Link><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.24em] text-yellow-400">Entrenador</p><h1 className="mt-2 text-3xl font-black">{trainer.name}</h1><p className="mt-1 text-zinc-400">{trainer.email}</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-bold ${trainer.status === "ACTIVE" ? "bg-emerald-400/10 text-emerald-300" : "bg-red-400/10 text-red-300"}`}>Acceso {trainer.status === "ACTIVE" ? "activo" : "suspendido"}</span></div><section className="mt-7 grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-zinc-800 bg-zinc-900/75 p-5"><h2 className="font-bold">Cuenta profesional</h2><dl className="mt-4 grid gap-3 text-sm"><div><dt className="text-zinc-500">Marca</dt><dd>{trainer.brandName || "Sin informar"}</dd></div><div><dt className="text-zinc-500">Teléfono</dt><dd>{trainer.phone || "Sin informar"}</dd></div><div><dt className="text-zinc-500">Ciudad / servicio</dt><dd>{[trainer.city, trainer.serviceType].filter(Boolean).join(" · ") || "Sin informar"}</dd></div><div><dt className="text-zinc-500">Workspace</dt><dd>{workspace?.name || "Sin workspace"} · {workspace?._count.students ?? 0} alumnos</dd></div><div><dt className="text-zinc-500">Onboarding</dt><dd>{trainer.onboardingCompleted ? "Completo" : "Pendiente"}</dd></div></dl></article><article className="rounded-2xl border border-yellow-400/15 bg-zinc-900/75 p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">Membresía</h2>{effective && <span className="rounded-full bg-yellow-400/10 px-2 py-1 text-xs font-bold text-yellow-300">{labels[effective]}</span>}</div>{subscription ? <dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-zinc-500">Plan</dt><dd>{subscription.plan}</dd></div><div><dt className="text-zinc-500">Inicio</dt><dd>{showDate(subscription.startedAt)}</dd></div><div><dt className="text-zinc-500">Último pago</dt><dd>{showDate(subscription.lastPaidAt)}</dd></div><div><dt className="text-zinc-500">Próximo vencimiento</dt><dd>{showDate(subscription.nextDueAt)}</dd></div><div><dt className="text-zinc-500">Fin del período</dt><dd>{showDate(subscription.currentPeriodEnd)}</dd></div><div className="col-span-2"><dt className="text-zinc-500">Notas internas</dt><dd className="whitespace-pre-wrap">{subscription.notes || "Sin notas"}</dd></div></dl> : <p className="mt-4 text-sm text-zinc-400">Sin membresía configurada.</p>}<TrainerMembershipDetailManager trainer={{ id: trainer.id, name: trainer.name }} subscription={serializedSubscription} /></article></section></div></main>;
}
