import test from "node:test";
import assert from "node:assert/strict";
import { buildRoutineAIContext, generateRoutineAIProposal, priorityCoverage, selectProposalDays, validateRoutineAIProposal } from "../lib/ai/routine-generation.ts";
import type { NormalizedEvaluation } from "../types/evaluation-read-model.ts";
import type { RoutineAIConstraints, RoutineAIContext } from "../types/routine-ai.ts";

const constraints: RoutineAIConstraints = { requestedDays: 2, sessionMinutes: 60, location: "SALON_BM", equipment: ["Mancuernas"], trainerInstructions: "Ejercicios simples" };
const context: RoutineAIContext = { studentId: "s1", serviceType: "PERSONALIZED", objective: "Fuerza", secondaryGoals: [], level: "principiante", weeklyAvailability: 2, activities: "", evaluation: { id: "e1", date: "2026-08-08", validity: "CURRENT", measures: {}, evolution: { bmIndex: null, changes: [] }, tests: [], asymmetries: [], bodyIssues: [{ zone: "Rodilla", side: "RIGHT", intensity: 2, status: "ACTIVE" }], priorities: [{ id: "core-endurance", category: "zona media", level: "atención", observed: "Plancha mejorable", interpretation: "Zona media mejorable", planningImpact: "Revisar", suggestion: "Trabajo progresivo" }], alerts: [], recommendations: [] } };
const exercise = { name: "Plancha frontal", muscleGroup: "Core", sets: 3, repetitions: "20-30", restSeconds: 60, effortType: "RIR", effortValue: 3, targetType: "REPS", targetSeconds: null, targetRepetitions: "", targetDistance: "", targetSide: "", equipment: "Colchoneta", alternativeExercise: "Dead bug", observations: "Revisar tolerancia", rationale: "Prioridad de zona media", evidenceIds: ["core-endurance"] };
const rawProposal = () => ({ summary: "Dos días de trabajo progresivo.", weeklyFrequency: 2, weeklyStructure: ["Día 1", "Día 2"], days: [1, 2].map((day) => ({ name: `Día ${day}`, focus: "Fuerza general", estimatedMinutes: 55, warmup: "Movilidad", notes: "Revisar tolerancia", blocks: [{ type: "STRENGTH", name: "Fuerza", rounds: null, durationSeconds: null, workSeconds: null, restSeconds: null, restBetweenRoundsSeconds: null, targetRounds: null, instructions: "Técnica controlada", exercises: [{ ...exercise }] }] })), rationale: [{ statement: "Dos días por disponibilidad", evidenceIds: ["weeklyAvailability"] }], warningsConsidered: ["Molestia informada: revisar tolerancia"], notes: [] });
const evaluation = (): NormalizedEvaluation => ({ id: "e1", studentId: "s1", studentName: "Nombre privado", date: "2026-08-08", version: 1, status: "COMPLETED", completionPercentage: 100, trainerName: "Coach", primaryGoal: "Fuerza", secondaryGoals: [], experienceLevel: "principiante", weeklyAvailability: "2 días", reassessmentDate: "", weight: 70, height: null, age: null, bmi: null, bodyFatPercentage: null, muscleMass: null, visceralFat: null, waist: null, hip: null, chest: null, rightArm: null, leftArm: null, rightThigh: null, leftThigh: null, rightCalf: null, leftCalf: null, activities: "Fútbol", habits: { private: true }, bodyIssues: [], testResults: [], finalStrengths: "privado", finalPriorities: "privado", finalLimitations: "privado", planningNotes: "privado", finalComment: "privado", createdAt: "", source: "PHYSICAL" });

test("el contexto usa reglas deterministas y excluye identidad y datos administrativos", () => { const built = buildRoutineAIContext({ id: "s1", serviceType: "PERSONALIZED", goal: "Fuerza" }, [evaluation()], "2026-08-08"); const serialized = JSON.stringify(built); assert.equal(built.evaluation?.id, "e1"); assert.ok(Array.isArray(built.evaluation?.priorities)); assert.doesNotMatch(serialized, /Nombre privado|trainerName|planningNotes|pagos|email|phone|habits/); });
test("PERSONALIZED y MIXED son elegibles; CLASSES se rechaza", () => { assert.equal(buildRoutineAIContext({ id: "s1", serviceType: "MIXED", goal: "Fuerza" }, [], "2026-08-08").serviceType, "MIXED"); assert.throws(() => buildRoutineAIContext({ id: "s1", serviceType: "CLASSES", goal: "Fuerza" }, [], "2026-08-08"), /SERVICE_NOT_ELIGIBLE/); });
test("acepta JSON válido y calcula cobertura determinista", () => { const result = validateRoutineAIProposal(rawProposal(), context, constraints, []); assert.ok(result.proposal); assert.deepEqual(result.proposal?.prioritiesCovered, ["core-endurance"]); assert.deepEqual(result.proposal?.prioritiesPending, []); });
test("rechaza JSON inválido, bloques desconocidos y cantidades inválidas", () => { assert.equal(validateRoutineAIProposal("texto", context, constraints, []).proposal, null); const block = rawProposal(); block.days[0].blocks[0].type = "MAGIC"; assert.equal(validateRoutineAIProposal(block, context, constraints, []).proposal, null); const volume = rawProposal(); volume.days[0].blocks[0].exercises[0].sets = 99; assert.equal(validateRoutineAIProposal(volume, context, constraints, []).proposal, null); });
test("nunca excede disponibilidad ni duración indicada", () => { const tooMany = rawProposal(); tooMany.weeklyFrequency = 3; tooMany.days.push(tooMany.days[0]); assert.match(validateRoutineAIProposal(tooMany, context, constraints, []).error, /frecuencia|disponibilidad/i); const tooLong = rawProposal(); tooLong.days[0].estimatedMinutes = 90; assert.match(validateRoutineAIProposal(tooLong, context, constraints, []).error, /duración/i); });
test("marca ejercicios desconocidos y volumen alto para revisión", () => { const raw = rawProposal(); raw.days.forEach((day) => { day.blocks[0].exercises = Array.from({ length: 8 }, (_, index) => ({ ...exercise, name: `Ejercicio inventado ${index}`, sets: 6 })); }); const result = validateRoutineAIProposal(raw, context, constraints, []); assert.ok(result.proposal?.validationWarnings.some((item) => item.includes("Volumen"))); assert.ok(result.proposal?.validationWarnings.some((item) => item.includes("revisión"))); assert.equal(result.proposal?.days[0].blocks[0].exercises[0].resolved, false); });
test("selección parcial copia días sin mutar la propuesta", () => { const proposal = validateRoutineAIProposal(rawProposal(), context, constraints, []).proposal!; const original = JSON.stringify(proposal); const selected = selectProposalDays(proposal, [proposal.days[1].id]); selected[0].name = "Editado"; assert.equal(selected.length, 1); assert.equal(JSON.stringify(proposal), original); });
test("regenerar reemplaza sólo la propuesta y nunca contiene estado activo", () => { const first = validateRoutineAIProposal(rawProposal(), context, constraints, []).proposal!; const secondRaw = rawProposal(); secondRaw.summary = "Regenerada"; const second = validateRoutineAIProposal(secondRaw, context, constraints, []).proposal!; assert.notEqual(first.summary, second.summary); assert.equal("status" in second, false); });
test("si el proveedor devuelve inválido una vez, reintenta y valida la segunda respuesta", async () => { const previous = { ...process.env }; process.env.NUTRITION_AI_BASE_URL = "https://provider.test"; process.env.NUTRITION_AI_API_KEY = "secret"; process.env.NUTRITION_AI_MODEL = "model"; let calls = 0; const fetchMock = async () => { calls += 1; return new Response(JSON.stringify({ choices: [{ message: { content: calls === 1 ? "{}" : JSON.stringify(rawProposal()) } }] }), { status: 200, headers: { "Content-Type": "application/json" } }); }; try { const result = await generateRoutineAIProposal(context, constraints, [], fetchMock as typeof fetch); assert.equal(result.proposal.days.length, 2); assert.equal(calls, 2); } finally { process.env = previous; } });
test("molestias permanecen en contexto y la cobertura pendiente no se inventa", () => { const raw = rawProposal(); raw.days.forEach((day) => { day.blocks[0].exercises = [{ ...exercise, name: "Sentadilla goblet", muscleGroup: "Cuádriceps", evidenceIds: [] }]; }); const proposal = validateRoutineAIProposal(raw, context, constraints, []).proposal!; const coverage = priorityCoverage(context, proposal.days); assert.deepEqual(coverage.covered, []); assert.deepEqual(coverage.pending, ["core-endurance"]); assert.equal(context.evaluation?.bodyIssues[0].zone, "Rodilla"); });
