"use client";

import { FormEvent, useMemo, useState } from "react";
import { ModuleShell, inputClass } from "@/componentes/module-shell";
import { useBrowserStore } from "@/lib/browser-store";
import type { Payment, PaymentStatus } from "@/types/gestion";

type StudentPlan = { name: string; plan: string; amount: number; dueDay: number };
const plans: StudentPlan[] = [{ name: "Martina López", plan: "Plan mensual", amount: 35000, dueDay: 5 }, { name: "Tomás García", plan: "Plan 3 veces por semana", amount: 28000, dueDay: 10 }, { name: "Carolina Ruiz", plan: "Plan mensual", amount: 35000, dueDay: 15 }];
const statuses: PaymentStatus[] = ["pagado", "pendiente", "vencido"];
const today = () => new Date().toISOString().slice(0, 10);
const money = (value: number) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 }).format(value);
const date = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("es-AR") : "—";
const blank = (student = plans[0]): Omit<Payment, "id"> => ({ student: student.name, amount: student.amount, concept: student.plan, dueDate: today(), paidDate: today(), method: "Transferencia", status: "pagado", notes: "" });

export default function PagosPage() {
  const { items, save, ready } = useBrowserStore<Payment>("bm-coach-payments", []);
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("todos"); const [form, setForm] = useState<Omit<Payment, "id">>(blank()); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Payment | null>(null); const [error, setError] = useState("");
  const studentState = useMemo(() => plans.map((plan) => { const current = items.filter((item) => item.student === plan.name).sort((a, b) => b.dueDate.localeCompare(a.dueDate))[0]; const due = current?.dueDate ?? new Date(new Date().getFullYear(), new Date().getMonth(), plan.dueDay).toISOString().slice(0, 10); const status: PaymentStatus = current?.status ?? (due < today() ? "vencido" : "pendiente"); return { ...plan, payment: current, due, status }; }), [items]);
  const visible = studentState.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()) && (filter === "todos" || item.status === filter));
  const owed = studentState.filter((item) => item.status !== "pagado"); const dueThisWeek = owed.filter((item) => { const days = Math.ceil((new Date(`${item.due}T12:00:00`).getTime() - new Date(`${today()}T12:00:00`).getTime()) / 86400000); return days >= 0 && days <= 7; });
  function openQuick(plan?: StudentPlan, payment?: Payment) { setEditing(payment ?? null); setForm(payment ? { student: payment.student, amount: payment.amount, concept: payment.concept, dueDate: payment.dueDate, paidDate: payment.paidDate || today(), method: payment.method, status: "pagado", notes: payment.notes } : blank(plan)); setError(""); setOpen(true); }
  function selectStudent(name: string) { const plan = plans.find((item) => item.name === name) ?? plans[0]; setForm((current) => ({ ...current, student: plan.name, amount: plan.amount, concept: plan.plan })); }
  function submit(event: FormEvent) { event.preventDefault(); if (!form.student || form.amount <= 0 || !form.dueDate || !form.paidDate) { setError("Completá el importe, vencimiento y fecha de pago."); return; } const next = editing ? items.map((item) => item.id === editing.id ? { ...form, id: item.id } : item) : [{ ...form, id: crypto.randomUUID() }, ...items]; save(next); setOpen(false); }
  function markPaid(item: { payment?: Payment; name: string; amount: number; plan: string; due: string }) { if (item.payment) save(items.map((payment) => payment.id === item.payment?.id ? { ...payment, status: "pagado", paidDate: today() } : payment)); else save([{ id: crypto.randomUUID(), student: item.name, amount: item.amount, concept: item.plan, dueDate: item.due, paidDate: today(), method: "Transferencia", status: "pagado", notes: "" }, ...items]); }
  return <ModuleShell title="Pagos" subtitle="Cobrá cuotas en segundos y detectá vencimientos a tiempo." action={<button onClick={() => openQuick()} className="rounded-xl bg-yellow-400 px-4 py-3 font-bold text-zinc-950">+ Registrar pago</button>}>
    <section className="grid gap-4 md:grid-cols-3"><Notice title="Deben pagar" value={owed.length} detail={owed.length ? owed.map((item) => item.name).join(" · ") : "Todos están al día"} tone="red" /><Notice title="Al día" value={studentState.filter((item) => item.status === "pagado").length} detail="Cuotas registradas como pagadas" tone="green" /><Notice title="Vencen esta semana" value={dueThisWeek.length} detail={dueThisWeek.length ? dueThisWeek.map((item) => item.name).join(" · ") : "Sin próximos vencimientos"} tone="yellow" /></section>
    <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-900"><div className="flex flex-col gap-3 border-b border-zinc-800 p-4 md:flex-row"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar alumno" className={inputClass} /><div className="flex flex-wrap gap-2">{["todos", ...statuses].map((status) => <button key={status} onClick={() => setFilter(status)} className={`rounded-lg px-3 py-2 text-sm capitalize ${filter === status ? "bg-yellow-400 font-bold text-zinc-950" : "bg-zinc-800 text-zinc-300"}`}>{status}</button>)}</div></div><div className="divide-y divide-zinc-800">{ready && visible.length === 0 ? <p className="p-10 text-center text-zinc-500">No encontramos alumnos con ese estado.</p> : visible.map((item) => <article key={item.name} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-semibold">{item.name}</h2><Status status={item.status} /></div><p className="mt-1 text-sm text-zinc-400">{item.plan} · {money(item.amount)} · vence {date(item.due)}</p></div><div className="flex gap-3"><button onClick={() => openQuick(item, item.payment)} className="rounded-lg border border-zinc-700 px-3 py-2 text-sm text-yellow-400">Registrar pago</button>{item.status !== "pagado" && <button onClick={() => markPaid(item)} className="rounded-lg bg-yellow-400 px-3 py-2 text-sm font-bold text-zinc-950">Marcar pagado</button>}</div></article>)}</div></section>
    {open && <PaymentModal form={form} selectStudent={selectStudent} setForm={setForm} error={error} close={() => setOpen(false)} submit={submit} editing={Boolean(editing)} />}
  </ModuleShell>;
}

function Notice({ title, value, detail, tone }: { title: string; value: number; detail: string; tone: "red" | "green" | "yellow" }) { const color = tone === "red" ? "text-red-300" : tone === "green" ? "text-emerald-300" : "text-yellow-300"; return <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-sm text-zinc-400">{title}</p><p className={`mt-1 text-3xl font-bold ${color}`}>{value}</p><p className="mt-2 text-xs text-zinc-500">{detail}</p></div>; }
function Status({ status }: { status: PaymentStatus }) { const tone = status === "pagado" ? "bg-emerald-400/15 text-emerald-300" : status === "vencido" ? "bg-red-400/15 text-red-300" : "bg-yellow-400/15 text-yellow-300"; return <span className={`rounded-full px-2 py-1 text-xs font-bold capitalize ${tone}`}>{status}</span>; }
function PaymentModal({ form, selectStudent, setForm, error, close, submit, editing }: { form: Omit<Payment, "id">; selectStudent: (name: string) => void; setForm: (form: Omit<Payment, "id">) => void; error: string; close: () => void; submit: (event: FormEvent) => void; editing: boolean }) { return <div className="fixed inset-0 z-20 grid place-items-center bg-black/80 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-zinc-900 p-6 text-white"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing ? "Actualizar pago" : "Registrar pago"}</h2><button type="button" onClick={close} className="text-zinc-400">Cerrar</button></div><p className="mt-2 text-sm text-zinc-400">Elegí el alumno: el plan completa el importe automáticamente.</p>{error && <p className="mt-4 rounded-lg bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}<div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">Alumno<select value={form.student} onChange={(event) => selectStudent(event.target.value)} className={`${inputClass} mt-1`}>{plans.map((plan) => <option key={plan.name}>{plan.name}</option>)}</select></label><label>Importe<input type="number" min="1" value={form.amount} onChange={(event) => setForm({ ...form, amount: Number(event.target.value) })} className={`${inputClass} mt-1`} /></label><label>Método<select value={form.method} onChange={(event) => setForm({ ...form, method: event.target.value })} className={`${inputClass} mt-1`}><option>Transferencia</option><option>Efectivo</option><option>Mercado Pago</option><option>Tarjeta</option></select></label><label>Vencimiento<input type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} className={`${inputClass} mt-1`} /></label><label>Fecha de pago<input type="date" value={form.paidDate} onChange={(event) => setForm({ ...form, paidDate: event.target.value })} className={`${inputClass} mt-1`} /></label></div><button className="mt-6 w-full rounded-xl bg-yellow-400 px-5 py-3 font-bold text-zinc-950">Confirmar pago</button></form></div>; }
