"use client";

import { FormEvent, useMemo, useState } from "react";
import { ModuleShell, inputClass } from "@/componentes/module-shell";
import { useBrowserStore } from "@/lib/browser-store";
import type { Payment, PaymentStatus } from "@/types/gestion";

const students = ["Martina López", "Tomás García", "Carolina Ruiz"];
const statuses: PaymentStatus[] = ["pagado", "pendiente", "vencido"];
const blank = (): Omit<Payment, "id"> => ({ student: students[0], amount: 0, concept: "Cuota mensual", dueDate: new Date().toISOString().slice(0, 10), paidDate: "", method: "Transferencia", status: "pendiente", notes: "" });
const money = (value: number) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 }).format(value);
const date = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("es-AR") : "—";

export default function PagosPage() {
  const { items, save, ready } = useBrowserStore<Payment>("bm-coach-payments", []);
  const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState("todos"); const [period, setPeriod] = useState("");
  const [form, setForm] = useState<Omit<Payment, "id">>(blank()); const [editing, setEditing] = useState<Payment | null>(null); const [viewing, setViewing] = useState<Payment | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const filtered = useMemo(() => items.filter((item) => item.student.toLowerCase().includes(query.toLowerCase()) && (statusFilter === "todos" || item.status === statusFilter) && (!period || item.dueDate.startsWith(period))), [items, query, statusFilter, period]);
  const totals = useMemo(() => items.reduce((sum, item) => ({ ...sum, [item.status]: sum[item.status] + item.amount }), { pagado: 0, pendiente: 0, vencido: 0 } as Record<PaymentStatus, number>), [items]);
  function change<K extends keyof Omit<Payment, "id">>(key: K, value: Omit<Payment, "id">[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function begin(item?: Payment) { setEditing(item ?? null); setForm(item ? { student: item.student, amount: item.amount, concept: item.concept, dueDate: item.dueDate, paidDate: item.paidDate, method: item.method, status: item.status, notes: item.notes } : blank()); setError(""); setOpen(true); }
  function submit(event: FormEvent) { event.preventDefault(); if (!form.student || !form.concept.trim() || form.amount <= 0 || !form.dueDate || (form.status === "pagado" && !form.paidDate)) { setError("Completá alumno, concepto, importe, vencimiento y fecha de pago si corresponde."); return; } const next = editing ? items.map((item) => item.id === editing.id ? { ...form, id: item.id } : item) : [{ ...form, id: crypto.randomUUID() }, ...items]; save(next); setOpen(false); }
  function remove(item: Payment) { if (window.confirm(`¿Eliminar el pago de ${item.student}?`)) save(items.filter((current) => current.id !== item.id)); }
  return <ModuleShell title="Pagos" subtitle="Control de cuotas, vencimientos y cobros por alumno." action={<button onClick={() => begin()} className="rounded-xl bg-yellow-400 px-4 py-3 font-bold text-zinc-950">+ Registrar pago</button>}>
    <section className="grid gap-4 md:grid-cols-3">{statuses.map((status) => <div key={status} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-sm capitalize text-zinc-400">Total {status}</p><p className="mt-2 text-2xl font-bold text-yellow-400">{money(totals[status])}</p></div>)}</section>
    <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-900"><div className="grid gap-3 border-b border-zinc-800 p-4 md:grid-cols-3"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por alumno" className={inputClass} /><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className={inputClass}><option value="todos">Todos los estados</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select><input type="month" value={period} onChange={(e) => setPeriod(e.target.value)} className={inputClass} /></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-zinc-500"><tr><th className="p-4">Alumno</th><th>Concepto</th><th>Importe</th><th>Vencimiento</th><th>Estado</th><th aria-label="Acciones" /></tr></thead><tbody>{ready && filtered.length === 0 ? <tr><td colSpan={6} className="p-12 text-center text-zinc-500">No hay pagos que coincidan con los filtros.</td></tr> : filtered.map((item) => <tr key={item.id} className="border-t border-zinc-800"><td className="p-4 font-medium">{item.student}</td><td>{item.concept}</td><td className="font-semibold">{money(item.amount)}</td><td>{date(item.dueDate)}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold capitalize ${item.status === "pagado" ? "bg-emerald-400/15 text-emerald-300" : item.status === "vencido" ? "bg-red-400/15 text-red-300" : "bg-yellow-400/15 text-yellow-300"}`}>{item.status}</span></td><td className="space-x-3 whitespace-nowrap pr-4 text-yellow-400"><button onClick={() => setViewing(item)}>Ver</button><button onClick={() => begin(item)}>Editar</button><button onClick={() => remove(item)} className="text-red-300">Eliminar</button></td></tr>)}</tbody></table></div></section>
    {open && <PaymentForm form={form} change={change} error={error} onClose={() => setOpen(false)} onSubmit={submit} editing={Boolean(editing)} />}{viewing && <PaymentDetail item={viewing} onClose={() => setViewing(null)} />}
  </ModuleShell>;
}

function PaymentForm({ form, change, error, onClose, onSubmit, editing }: { form: Omit<Payment, "id">; change: <K extends keyof Omit<Payment, "id">>(key: K, value: Omit<Payment, "id">[K]) => void; error: string; onClose: () => void; onSubmit: (event: FormEvent) => void; editing: boolean }) { return <div className="fixed inset-0 z-20 overflow-auto bg-black/80 p-4"><form onSubmit={onSubmit} className="mx-auto my-8 max-w-3xl rounded-2xl bg-zinc-900 p-6 text-white"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing ? "Editar pago" : "Registrar pago"}</h2><button type="button" onClick={onClose} className="text-zinc-400">Cerrar</button></div>{error && <p className="mt-4 rounded-lg bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}<div className="mt-5 grid gap-4 md:grid-cols-2"><label>Alumno<select value={form.student} onChange={(e) => change("student", e.target.value)} className={`${inputClass} mt-1`}>{students.map((student) => <option key={student}>{student}</option>)}</select></label><label>Concepto<input required value={form.concept} onChange={(e) => change("concept", e.target.value)} className={`${inputClass} mt-1`} /></label><label>Importe<input required min="0.01" type="number" value={form.amount || ""} onChange={(e) => change("amount", Number(e.target.value))} className={`${inputClass} mt-1`} /></label><label>Estado<select value={form.status} onChange={(e) => change("status", e.target.value as PaymentStatus)} className={`${inputClass} mt-1`}>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><label>Vencimiento<input required type="date" value={form.dueDate} onChange={(e) => change("dueDate", e.target.value)} className={`${inputClass} mt-1`} /></label><label>Fecha de pago<input type="date" value={form.paidDate} onChange={(e) => change("paidDate", e.target.value)} className={`${inputClass} mt-1`} /></label><label>Método de pago<select value={form.method} onChange={(e) => change("method", e.target.value)} className={`${inputClass} mt-1`}><option>Transferencia</option><option>Efectivo</option><option>Tarjeta</option><option>Mercado Pago</option></select></label></div><label className="mt-4 block">Observaciones<textarea value={form.notes} onChange={(e) => change("notes", e.target.value)} rows={3} className={`${inputClass} mt-1`} /></label><button className="mt-6 rounded-xl bg-yellow-400 px-5 py-3 font-bold text-zinc-950">Guardar pago</button></form></div>; }
function PaymentDetail({ item, onClose }: { item: Payment; onClose: () => void }) { return <div className="fixed inset-0 z-20 grid place-items-center bg-black/80 p-4"><section className="w-full max-w-lg rounded-2xl bg-zinc-900 p-6 text-white"><div className="flex justify-between"><h2 className="text-xl font-bold">Detalle del pago</h2><button onClick={onClose} className="text-zinc-400">Cerrar</button></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-zinc-500">Alumno</dt><dd>{item.student}</dd></div><div><dt className="text-zinc-500">Importe</dt><dd>{money(item.amount)}</dd></div><div><dt className="text-zinc-500">Concepto</dt><dd>{item.concept}</dd></div><div><dt className="text-zinc-500">Estado</dt><dd className="capitalize">{item.status}</dd></div><div><dt className="text-zinc-500">Vencimiento</dt><dd>{date(item.dueDate)}</dd></div><div><dt className="text-zinc-500">Fecha de pago</dt><dd>{date(item.paidDate)}</dd></div><div><dt className="text-zinc-500">Método</dt><dd>{item.method}</dd></div><div><dt className="text-zinc-500">Observaciones</dt><dd>{item.notes || "—"}</dd></div></dl></section></div>; }
