"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useBrowserStore } from "@/lib/browser-store";
import type { CoachEvent, Payment, Student } from "@/types/gestion";

const modules = [["Alumnos", "Gestionar alumnos.", "/alumnos"], ["Rutinas", "Crear rutinas.", "/rutinas"], ["Clases", "Organizar horarios.", "/clases"], ["Pagos", "Control de cuotas y vencimientos.", "/pagos"], ["Eventos", "Planificar actividades y encuentros.", "/eventos"], ["Evaluaciones", "Seguimiento físico.", "/evaluaciones"], ["Configuración", "Ajustes del sistema.", "/configuracion"]];
const money = (value: number) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 }).format(value);
const today = new Date().toISOString().slice(0, 10);

export default function Home() {
  const { items: payments } = useBrowserStore<Payment>("bm-coach-payments", []); const { items: events } = useBrowserStore<CoachEvent>("bm-coach-events", []); const { items: students } = useBrowserStore<Student>("bm-coach-students", []); const [todayClasses, setTodayClasses] = useState(0);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { fetch("/api/clases").then((response) => response.ok ? response.json() : []).then((items: { date: string }[]) => setTodayClasses(items.filter((item) => item.date === today).length)).catch(() => setTodayClasses(0)); }); return () => window.cancelAnimationFrame(frame); }, []);
  const stats = useMemo(() => ({ pending: payments.filter((item) => item.status !== "pagado").length, income: payments.filter((item) => item.status === "pagado" && item.paidDate.startsWith(today.slice(0, 7))).reduce((sum, item) => sum + item.amount, 0), expired: payments.filter((item) => item.status === "vencido"), upcoming: events.filter((item) => item.status !== "cancelado" && item.date >= today).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 3) }), [events, payments]);
  return <main className="min-h-screen bg-zinc-950 p-6 text-white md:p-10"><div className="mx-auto max-w-6xl"><header className="mb-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-yellow-400">BM Coach</p><h1 className="mt-2 text-4xl font-bold">Panel de administración</h1><p className="mt-2 text-zinc-400">Una mirada rápida a tu actividad de hoy.</p></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Alumnos activos" value={String(students.filter((student) => student.status === "activo").length)} href="/alumnos" /><Metric label="Pagos pendientes" value={String(stats.pending)} href="/pagos" tone={stats.pending ? "yellow" : undefined} /><Metric label="Ingresos del mes" value={money(stats.income)} href="/pagos" /><Metric label="Clases de hoy" value={String(todayClasses)} href="/clases" /></section><section className="mt-6 grid gap-5 lg:grid-cols-2"><aside className="rounded-2xl border border-red-400/30 bg-red-400/5 p-5"><h2 className="font-semibold text-red-200">Cuotas vencidas</h2><p className="mt-1 text-sm text-zinc-400">Revisá estos pagos para no perder seguimiento.</p><div className="mt-4 space-y-2">{stats.expired.length ? stats.expired.map((item) => <Link key={item.id} href="/pagos" className="flex justify-between rounded-lg bg-zinc-900 p-3 text-sm"><span>{item.student}</span><span className="text-red-300">{money(item.amount)}</span></Link>) : <p className="text-sm text-emerald-300">No hay cuotas vencidas.</p>}</div></aside><aside className="rounded-2xl border border-yellow-400/30 bg-yellow-400/5 p-5"><h2 className="font-semibold text-yellow-300">Próximos eventos</h2><p className="mt-1 text-sm text-zinc-400">Recordatorios de tu agenda próxima.</p><div className="mt-4 space-y-2">{stats.upcoming.length ? stats.upcoming.map((item) => <Link key={item.id} href="/eventos" className="block rounded-lg bg-zinc-900 p-3 text-sm"><span className="font-medium">{item.title}</span><span className="ml-2 text-zinc-400">{new Date(`${item.date}T12:00:00`).toLocaleDateString("es-AR")}, {item.startTime}</span></Link>) : <p className="text-sm text-zinc-400">No hay eventos próximos.</p>}</div></aside></section><section className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{modules.map(([title, description, href]) => <Link key={href} href={href} className="group rounded-2xl border border-zinc-800 bg-zinc-900 p-6 transition hover:-translate-y-1 hover:border-yellow-400/70"><h2 className="text-xl font-semibold group-hover:text-yellow-400">{title}</h2><p className="mt-2 text-sm text-zinc-400">{description}</p><span className="mt-5 inline-block text-sm font-semibold text-yellow-400">Abrir módulo →</span></Link>)}</section></div></main>;
}

function Metric({ label, value, href, tone }: { label: string; value: string; href: string; tone?: "yellow" }) { return <Link href={href} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5 transition hover:border-yellow-400/70"><p className="text-sm text-zinc-400">{label}</p><p className={`mt-2 text-2xl font-bold ${tone ? "text-yellow-400" : "text-white"}`}>{value}</p></Link>; }
