export const NUTRITION_EDUCATION = [
  {
    id: "protein-basics",
    category: "Proteína",
    title: "Cómo sumar proteína sin complicarte",
    summary: "Ideas prácticas para incluir una fuente de proteína en las comidas principales.",
    body: "La proteína puede aparecer en huevos, carnes, lácteos, legumbres, tofu y otras opciones. No hace falta que todas las comidas sean iguales: elegí alternativas compatibles con tus preferencias y organizá las que puedas sostener.",
    durationMinutes: 3,
  },
  {
    id: "hydration-routine",
    category: "Hidratación",
    title: "Hidratación como hábito",
    summary: "Usá señales simples durante el día en lugar de esperar a tener mucha sed.",
    body: "Tener agua visible, llevar una botella y beber con las comidas son recordatorios sencillos. El clima, el entrenamiento y la transpiración pueden cambiar tus necesidades, por eso evitamos una cifra rígida para todas las personas.",
    durationMinutes: 2,
  },
  {
    id: "pre-training",
    category: "Preentrenamiento",
    title: "Cómo llegar con energía al entrenamiento",
    summary: "Organizá una comida conocida y tolerable sin buscar fórmulas extremas.",
    body: "Si pasaron muchas horas desde tu última comida, una opción sencilla con carbohidratos y algo de proteína puede ayudarte a llegar mejor. La cantidad y el horario dependen de tu tolerancia y de cuánto falta para entrenar.",
    durationMinutes: 3,
  },
  {
    id: "post-training",
    category: "Postentrenamiento",
    title: "Recuperación después de entrenar",
    summary: "Volvé a una comida completa e hidratación regular.",
    body: "Después de entrenar podés priorizar una comida que combine proteína, carbohidratos, vegetales y líquidos. No hace falta usar productos especiales cuando una comida cotidiana resuelve la situación.",
    durationMinutes: 3,
  },
  {
    id: "shopping-organization",
    category: "Compras",
    title: "Una compra que facilite la semana",
    summary: "Elegí bases versátiles y reducí decisiones de último momento.",
    body: "Combiná fuentes de proteína, cereales o legumbres, frutas, verduras y alimentos de almacén que uses con frecuencia. Repetir algunos ingredientes en varias preparaciones ayuda a reducir desperdicio.",
    durationMinutes: 4,
  },
  {
    id: "consistency",
    category: "Constancia",
    title: "Constancia antes que perfección",
    summary: "Una semana útil no necesita ser perfecta.",
    body: "Los hábitos se construyen con decisiones repetibles. Si un día cambia, retomá en la próxima comida sin compensaciones extremas ni culpa.",
    durationMinutes: 2,
  },
] as const;
