import type { WeeklyMissionView } from "./weekly-mission.ts";

export type CelebrationAchievement = {
  notificationId: string;
  id: string;
  icon: string;
  name: string;
  description: string;
  exercise: string | null;
  previousValue: string | null;
  newValue: string | null;
  unlockedAt: string;
  points: number;
};

export type CelebratableWeeklyMission = WeeklyMissionView & { celebrationConfirmed?: boolean };
export type PortalCelebration =
  | { kind: "weekly"; key: string; mission: CelebratableWeeklyMission }
  | { kind: "achievement"; key: string; achievement: CelebrationAchievement };

// pointsAwardedAt is regenerated by the existing reconciliation after revocation.
// completedAt alone is the class date and can repeat for a new valid completion.
export function weeklyCelebrationKey(mission: CelebratableWeeklyMission | null) {
  if (!mission || mission.state !== "COMPLETED" || mission.progress < mission.target || !mission.pointsAwardedAt) return null;
  return `__weekly-celebration:v1__:${mission.id}:${mission.pointsAwardedAt}`;
}

export function weeklyCelebrationConfirmed(mission: CelebratableWeeklyMission | null, confirmed: ReadonlySet<string>) {
  const key = weeklyCelebrationKey(mission);
  return Boolean(key && (mission?.celebrationConfirmed || confirmed.has(key)));
}

export function enqueueCelebrations(queue: PortalCelebration[], incoming: PortalCelebration[], confirmed: ReadonlySet<string>) {
  const keys = new Set(queue.map(item => item.key));
  const additions = incoming.filter(item => {
    if (keys.has(item.key) || confirmed.has(item.key)) return false;
    keys.add(item.key);
    return true;
  });
  return additions.length ? [...queue, ...additions] : queue;
}

export function reconcileWeeklyCelebration(queue: PortalCelebration[], mission: CelebratableWeeklyMission | null, confirmed: ReadonlySet<string>) {
  const key = weeklyCelebrationKey(mission);
  const eligible = key && !weeklyCelebrationConfirmed(mission, confirmed);
  const remaining = queue.filter(item => item.kind !== "weekly" || (eligible && item.key === key));
  return eligible && mission ? enqueueCelebrations(remaining, [{ kind: "weekly", key, mission }], confirmed) : remaining;
}
