import { randomUUID } from "node:crypto";
import { requestCompatibleChat } from "../nutrition-ai-core.ts";
import { compareEvaluations } from "../evaluation-progress.ts";
import { interpretEvaluation } from "../evaluation-interpretation.ts";
import { selectEvaluationForPlanning } from "../evaluation-read-model.ts";
import type { NormalizedEvaluation } from "../../types/evaluation-read-model.ts";
import type { RoutineAIBlock, RoutineAIConstraints, RoutineAIContext, RoutineAIDay, RoutineAIExercise, RoutineAIProposal, RoutineExerciseCatalogEntry } from "../../types/routine-ai.ts";

type StudentContextInput = { id: string; serviceType: string; goal: string; level?: string };
const BLOCK_TYPES = ["STRENGTH", "INTERVAL", "EMOM", "AMRAP", "FOR_TIME"] as const;
const TARGET_TYPES = ["TIME", "REPS", "DISTANCE", "REST", "FREE"] as const;
const text = (value: unknown, max = 500) => typeof value === "string" ? value.trim().slice(0, max) : "";
const number = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value : null;
const integer = (value: unknown, min: number, max: number) => { const parsed = number(value); return parsed !== null && Number.isInteger(parsed) && parsed >= min && parsed <= max ? parsed : null; };
export const normalizeExerciseName = (value: string) => value.normalize("NFD").replace(/\p{Diacritic}/gu, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

export const DEFAULT_ROUTINE_EXERCISES: RoutineExerciseCatalogEntry[] = [
  { name: "Sentadilla goblet", aliases: ["Goblet squat"] }, { name: "Sentadilla a cajón", aliases: ["Box squat"] },
  { name: "Peso muerto rumano", aliases: ["RDL"] }, { name: "Puente de glúteos", aliases: ["Glute bridge"] },
  { name: "Hip thrust", aliases: ["Empuje de cadera"] }, { name: "Remo con mancuerna", aliases: ["Remo unilateral"] },
  { name: "Press de pecho con mancuernas", aliases: ["Press plano mancuernas"] }, { name: "Press militar con mancuernas", aliases: ["Press hombros"] },
  { name: "Jalón al pecho", aliases: ["Lat pulldown"] }, { name: "Flexiones", aliases: ["Push ups", "Flexiones estándar"] },
  { name: "Plancha frontal", aliases: ["Plank"] }, { name: "Plancha lateral", aliases: ["Side plank"] },
  { name: "Bird dog", aliases: [] }, { name: "Dead bug", aliases: [] }, { name: "Equilibrio unipodal", aliases: [] },
  { name: "Rodilla a la pared", aliases: ["Movilidad de tobillo"] }, { name: "Caminata", aliases: [] },
];

function weeklyAvailability(value: string) { const parsed = value.match(/\d+/)?.[0]; return parsed ? Math.max(1, Math.min(7, Number(parsed))) : null; }

export function buildRoutineAIContext(student: StudentContextInput, evaluations: NormalizedEvaluation[], today: string): RoutineAIContext {
  if (student.serviceType !== "PERSONALIZED" && student.serviceType !== "MIXED") throw new Error("SERVICE_NOT_ELIGIBLE");
  const ordered = [...evaluations].sort((a, b) => b.date.localeCompare(a.date) || b.version - a.version); const latest = selectEvaluationForPlanning(ordered); const previous = ordered.find((item) => item.id !== latest?.id);
  if (!latest) return { studentId: student.id, serviceType: student.serviceType, objective: student.goal, secondaryGoals: [], level: student.level ?? "", weeklyAvailability: null, activities: "", evaluation: null };
  const interpretation = interpretEvaluation(latest, today); const comparison = previous ? compareEvaluations(previous, latest, today) : null;
  const measures = Object.fromEntries(([['weight',latest.weight],['waist',latest.waist],['hip',latest.hip],['chest',latest.chest],['bodyFatPercentage',latest.bodyFatPercentage]] as Array<[string, number | null]>).filter((item): item is [string, number] => item[1] !== null));
  return { studentId: student.id, serviceType: student.serviceType, objective: latest.primaryGoal || student.goal, secondaryGoals: latest.secondaryGoals, level: latest.experienceLevel || student.level || "", weeklyAvailability: weeklyAvailability(latest.weeklyAvailability), activities: latest.activities, evaluation: { id: latest.id, date: latest.date, validity: interpretation.validity, measures, evolution: { bmIndex: comparison?.progress.score ?? null, changes: comparison?.measurements.map((item) => ({ metric: item.label, change: item.absoluteChange, unit: item.unit })) ?? [] }, tests: latest.testResults.map((item) => ({ key: item.testKey, category: item.category, status: item.status, value: item.numericValue, unit: item.unit, right: item.rightValue, left: item.leftValue })), asymmetries: interpretation.asymmetries.filter((item) => item.relevant).map((item) => ({ testKey: item.testKey, difference: item.absoluteDifference, unit: item.unit, lowerSide: item.lowerSide })), bodyIssues: latest.bodyIssues.map((item) => ({ zone: item.bodyZone, side: item.side, intensity: item.intensity, status: item.status })), priorities: interpretation.priorities.map((item) => ({ id: item.id, category: item.category, level: item.level, observed: item.evidence, interpretation: item.message, planningImpact: `Revisar la planificación de ${item.category} sin convertir el dato en diagnóstico.`, suggestion: item.recommendation })), alerts: interpretation.alerts.map((item) => ({ id: item.id, message: item.message })), recommendations: interpretation.recommendations } };
}

export function routineAISystemInstructions() {
  return ["Sos un asistente de planificación de BM Training para uso exclusivo del entrenador.", "Las reglas deterministas del contexto son obligatorias y tienen prioridad.", "No diagnostiques, no prescribas tratamientos, no inventes lesiones, mediciones ni equipamiento.", "Usá lenguaje condicional ante molestias: revisar tolerancia, considerar alternativa o adaptar si genera molestia.", "Respondé sólo JSON válido y usá únicamente STRENGTH, INTERVAL, EMOM, AMRAP o FOR_TIME.", "Nunca actives ni guardes una rutina; sólo devolvé una propuesta revisable.", "Cada justificación debe incluir evidenceIds existentes en el contexto.", "No generes más días que la disponibilidad ni volúmenes extremos."].join(" ");
}

export function buildRoutineAIPrompt(context: RoutineAIContext, constraints: RoutineAIConstraints, catalog: RoutineExerciseCatalogEntry[]) {
  return { context, constraints: { ...constraints, trainerInstructions: text(constraints.trainerInstructions, 800) }, exerciseCatalog: catalog.slice(0, 250), expected: { summary: "string", weeklyFrequency: "number", weeklyStructure: ["string"], days: [{ name: "string", focus: "string", estimatedMinutes: "number|null", warmup: "string", notes: "string", blocks: [{ type: BLOCK_TYPES, name: "string", rounds: "number|null", durationSeconds: "number|null", workSeconds: "number|null", restSeconds: "number|null", restBetweenRoundsSeconds: "number|null", targetRounds: "number|null", instructions: "string", exercises: [{ name: "string", muscleGroup: "string", sets: "1..6", repetitions: "string", restSeconds: "0..300|null", effortType: "RIR|RPE", effortValue: "0..10|null", targetType: TARGET_TYPES, targetSeconds: "number|null", targetRepetitions: "string", targetDistance: "string", targetSide: "string", equipment: "string", alternativeExercise: "string", observations: "string", rationale: "string breve", evidenceIds: ["priority/alert/objective ids"] }] }] }], rationale: [{ statement: "string", evidenceIds: ["string"] }], warningsConsidered: ["string"], notes: ["string"] } };
}

function resolver(catalog: RoutineExerciseCatalogEntry[]) { const names = new Map<string, { name: string; source: "CATALOG" | "KNOWN_NAME" }>(); for (const item of [...DEFAULT_ROUTINE_EXERCISES.map((entry) => ({ ...entry, source: "CATALOG" as const })), ...catalog.map((entry) => ({ ...entry, source: "KNOWN_NAME" as const }))]) for (const alias of [item.name, ...item.aliases]) names.set(normalizeExerciseName(alias), { name: item.name, source: item.source }); return names; }
function nullableInteger(value: unknown, min: number, max: number) { return value === null || value === undefined ? null : integer(value, min, max); }

function sanitizeExercise(value: unknown, catalog: RoutineExerciseCatalogEntry[]): RoutineAIExercise | null {
  if (!value || typeof value !== "object") return null; const raw = value as Record<string, unknown>; const name = text(raw.name, 120); const muscleGroup = text(raw.muscleGroup, 80); const sets = integer(raw.sets, 1, 6); const repetitions = text(raw.repetitions, 30); const effortType = raw.effortType === "RPE" ? "RPE" : raw.effortType === "RIR" ? "RIR" : null; const targetType = TARGET_TYPES.includes(raw.targetType as typeof TARGET_TYPES[number]) ? raw.targetType as typeof TARGET_TYPES[number] : null;
  if (!name || !muscleGroup || sets === null || !repetitions || !effortType || !targetType) return null; const match = resolver(catalog).get(normalizeExerciseName(name));
  return { id: randomUUID(), name: match?.name ?? name, muscleGroup, sets, repetitions, restSeconds: nullableInteger(raw.restSeconds, 0, 300), effortType, effortValue: raw.effortValue === null || raw.effortValue === undefined ? null : number(raw.effortValue) !== null && number(raw.effortValue)! >= 0 && number(raw.effortValue)! <= 10 ? number(raw.effortValue) : null, targetType, targetSeconds: nullableInteger(raw.targetSeconds, 1, 3600), targetRepetitions: text(raw.targetRepetitions, 30), targetDistance: text(raw.targetDistance, 50), targetSide: text(raw.targetSide, 50), equipment: text(raw.equipment, 120), alternativeExercise: text(raw.alternativeExercise, 120), observations: text(raw.observations, 500), rationale: text(raw.rationale, 350), evidenceIds: Array.isArray(raw.evidenceIds) ? raw.evidenceIds.map((item) => text(item, 100)).filter(Boolean).slice(0, 8) : [], resolved: Boolean(match), resolutionSource: match?.source ?? "UNRESOLVED" };
}

function sanitizeBlock(value: unknown, catalog: RoutineExerciseCatalogEntry[]): RoutineAIBlock | null {
  if (!value || typeof value !== "object") return null; const raw = value as Record<string, unknown>; if (!BLOCK_TYPES.includes(raw.type as typeof BLOCK_TYPES[number])) return null; const exercises = Array.isArray(raw.exercises) ? raw.exercises.map((item) => sanitizeExercise(item, catalog)).filter((item): item is RoutineAIExercise => Boolean(item)) : [];
  if (!text(raw.name, 120) || !exercises.length || exercises.length > 8) return null; return { id: randomUUID(), type: raw.type as RoutineAIBlock["type"], name: text(raw.name, 120), rounds: nullableInteger(raw.rounds, 1, 10), durationSeconds: nullableInteger(raw.durationSeconds, 30, 3600), workSeconds: nullableInteger(raw.workSeconds, 5, 600), restSeconds: nullableInteger(raw.restSeconds, 0, 600), restBetweenRoundsSeconds: nullableInteger(raw.restBetweenRoundsSeconds, 0, 900), targetRounds: nullableInteger(raw.targetRounds, 1, 20), instructions: text(raw.instructions, 1000), exercises };
}

function sanitizeDay(value: unknown, catalog: RoutineExerciseCatalogEntry[]): RoutineAIDay | null { if (!value || typeof value !== "object") return null; const raw = value as Record<string, unknown>; const blocks = Array.isArray(raw.blocks) ? raw.blocks.map((item) => sanitizeBlock(item, catalog)).filter((item): item is RoutineAIBlock => Boolean(item)) : []; if (!text(raw.name, 100) || !blocks.length || blocks.length > 5) return null; return { id: randomUUID(), name: text(raw.name, 100), focus: text(raw.focus, 200), estimatedMinutes: nullableInteger(raw.estimatedMinutes, 15, 180), warmup: text(raw.warmup, 1000), notes: text(raw.notes, 500), blocks }; }

export function priorityCoverage(context: RoutineAIContext, days: RoutineAIDay[]) { const priorities = context.evaluation?.priorities ?? []; const all = days.flatMap((day) => day.blocks.flatMap((block) => block.exercises.map((exercise) => ({ block, exercise })))); const covered = priorities.filter((priority) => all.some(({ block, exercise }) => { const value = normalizeExerciseName(`${exercise.name} ${exercise.muscleGroup} ${exercise.targetSide}`); if (priority.id === "ankle-mobility") return /rodilla pared|movilidad tobillo/.test(value); if (priority.id === "core-endurance" || priority.category === "zona media") return /core|plancha|dead bug|bird dog/.test(value); if (priority.category === "movilidad") return /movilidad|rodilla pared|rotacion/.test(value); if (priority.category === "equilibrio") return /equilibrio|unipodal/.test(value); if (priority.category === "asimetría") return /unilateral|derecha|izquierda/.test(value); if (priority.category === "fuerza") return block.type === "STRENGTH"; return exercise.evidenceIds.includes(priority.id); })); const coveredIds = covered.map((item) => item.id); return { covered: coveredIds, pending: priorities.map((item) => item.id).filter((id) => !coveredIds.includes(id)) }; }

export function validateRoutineAIProposal(value: unknown, context: RoutineAIContext, constraints: RoutineAIConstraints, catalog: RoutineExerciseCatalogEntry[], now = new Date().toISOString()): { proposal: RoutineAIProposal | null; error: string } {
  if (!value || typeof value !== "object") return { proposal: null, error: "La IA no devolvió un objeto JSON." }; const raw = value as Record<string, unknown>; const requestedLimit = Math.min(constraints.requestedDays, context.weeklyAvailability ?? constraints.requestedDays); const frequency = integer(raw.weeklyFrequency, 1, requestedLimit); const days = Array.isArray(raw.days) ? raw.days.map((item) => sanitizeDay(item, catalog)).filter((item): item is RoutineAIDay => Boolean(item)) : [];
  if (frequency === null || days.length !== frequency || days.length > requestedLimit) return { proposal: null, error: "La frecuencia o los días no respetan la disponibilidad." }; if (days.some((day) => constraints.sessionMinutes !== null && day.estimatedMinutes !== null && day.estimatedMinutes > constraints.sessionMinutes + 15)) return { proposal: null, error: "Una sesión excede la duración indicada." };
  const weeklySets = days.flatMap((day) => day.blocks).filter((block) => block.type === "STRENGTH").flatMap((block) => block.exercises).reduce((sum, exercise) => sum + exercise.sets, 0); const exerciseCount = days.flatMap((day) => day.blocks.flatMap((block) => block.exercises)).length; const unresolved = days.flatMap((day) => day.blocks.flatMap((block) => block.exercises)).filter((item) => !item.resolved); const warnings = [...(weeklySets > 80 ? [`Volumen semanal alto: ${weeklySets} series.`] : []), ...(exerciseCount > 40 ? [`Cantidad alta de ejercicios: ${exerciseCount}.`] : []), ...(unresolved.length ? [`${unresolved.length} ejercicios requieren revisión de nombre.`] : [])]; const coverage = priorityCoverage(context, days);
  const strings = (candidate: unknown, max = 12) => Array.isArray(candidate) ? candidate.map((item) => text(item, 300)).filter(Boolean).slice(0, max) : [];
  const rationale = Array.isArray(raw.rationale) ? raw.rationale.flatMap((item) => item && typeof item === "object" ? [{ statement: text((item as Record<string, unknown>).statement, 400), evidenceIds: strings((item as Record<string, unknown>).evidenceIds, 8) }] : []).filter((item) => item.statement) : [];
  return { proposal: { summary: text(raw.summary, 800), weeklyFrequency: frequency, weeklyStructure: strings(raw.weeklyStructure, 7), days, rationale, prioritiesCovered: coverage.covered, prioritiesPending: coverage.pending, warningsConsidered: strings(raw.warningsConsidered), notes: strings(raw.notes), validationWarnings: warnings, generatedAt: now }, error: "" };
}

function parseJSON(content: string) { const cleaned = content.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, ""); return JSON.parse(cleaned) as unknown; }
function providerConfiguration() { const endpoint = process.env.NUTRITION_AI_BASE_URL?.trim(); const apiKey = process.env.NUTRITION_AI_API_KEY?.trim(); const model = process.env.NUTRITION_AI_MODEL?.trim(); if (!endpoint || !apiKey || !model || process.env.ROUTINE_AI_ENABLED?.trim().toLowerCase() === "false") throw new Error("AI_NOT_CONFIGURED"); return { endpoint, apiKey, model }; }

export function routineAIErrorDescriptor(error: unknown) {
  const raw = error instanceof Error ? error.message : "AI_FAILED";
  if (raw === "DAILY_LIMIT") return { code: "DAILY_LIMIT", status: 429, message: "Alcanzaste el límite diario de propuestas con IA." };
  if (raw === "DUPLICATE_REQUEST") return { code: "DUPLICATE_REQUEST", status: 409, message: "Esta solicitud ya está en proceso." };
  if (raw.startsWith("AI_INVALID_RESPONSE")) return { code: "INVALID_RESPONSE", status: 422, message: "La respuesta generada no pudo validarse. Regenerá o continuá manualmente." };
  if (error instanceof DOMException && error.name === "AbortError" || /abort|timeout/i.test(raw)) return { code: "TIMEOUT", status: 504, message: "La generación tardó demasiado. Probá nuevamente." };
  if (raw === "AI_NOT_CONFIGURED" || raw.startsWith("AI_HTTP")) return { code: "PROVIDER", status: 502, message: "No pudimos generar la propuesta en este momento. Probá nuevamente." };
  return { code: "AI_FAILED", status: 502, message: "No pudimos generar la propuesta en este momento. Podés continuar manualmente." };
}

export async function generateRoutineAIProposal(context: RoutineAIContext, constraints: RoutineAIConstraints, catalog: RoutineExerciseCatalogEntry[], fetchImpl: typeof fetch = fetch) { const provider = providerConfiguration(); const prompt = buildRoutineAIPrompt(context, constraints, catalog); const messages = [{ role: "system", content: routineAISystemInstructions() }, { role: "user", content: JSON.stringify(prompt) }]; let lastError = "INVALID_RESPONSE"; for (let attempt = 0; attempt < 2; attempt += 1) { const response = await requestCompatibleChat({ endpoint: provider.endpoint, apiKey: provider.apiKey, timeoutMs: Math.max(3000, Math.min(Number(process.env.NUTRITION_AI_TIMEOUT_MS) || 12000, 30000)), fetchImpl, body: { model: provider.model, temperature: 0.25, response_format: { type: "json_object" }, max_tokens: Math.max(800, Math.min(Number(process.env.ROUTINE_AI_MAX_OUTPUT_TOKENS) || 3000, 5000)), messages: attempt === 0 ? messages : [...messages, { role: "assistant", content: "La respuesta anterior fue inválida." }, { role: "user", content: `Corregí el JSON respetando el schema. Error: ${lastError}` }] } }); try { const validated = validateRoutineAIProposal(parseJSON(response.content), context, constraints, catalog); if (validated.proposal) return { proposal: validated.proposal, model: provider.model, usage: response.usage }; lastError = validated.error; } catch { lastError = "JSON inválido"; } } throw new Error(`AI_INVALID_RESPONSE:${lastError}`); }

export function selectProposalDays(proposal: RoutineAIProposal, selectedDayIds: string[]) { const selected = new Set(selectedDayIds); return proposal.days.filter((day) => selected.has(day.id)).map((day) => structuredClone(day)); }

export function exerciseAlternatives(exerciseName: string, catalog: RoutineExerciseCatalogEntry[], limit = 4) { const current = normalizeExerciseName(exerciseName); return [...DEFAULT_ROUTINE_EXERCISES, ...catalog].filter((item) => normalizeExerciseName(item.name) !== current).slice(0, Math.max(2, Math.min(limit, 4))).map((item) => item.name); }
